import { useEffect, useState } from 'react';
import { getApiToken } from './auth';

type Field={id:string;code:string};
type SoilSample={id:string;sample_code:string;sampled_on:string;field_code:string;ph:string|number|null;organic_matter_g_dm3:string|number|null;phosphorus_mg_dm3:string|number|null;potassium_mmolc_dm3:string|number|null;base_saturation_pct:string|number|null;laboratory:string|null};
type SoilSummary={samples:string|number;sampled_fields:string|number;avg_ph:string|number|null;avg_organic_matter:string|number|null;avg_phosphorus:string|number|null;avg_potassium:string|number|null;avg_base_saturation:string|number|null;latest_sample:string|null};
type Pest={id:string;field_code:string;category:string;name:string;observed_on:string;severity:number;infestation_pct:string|number|null;infested_area_ha:string|number|null;status:string;action_count:string|number;notes:string|null};
type PestSummary={active:string|number;high_severity:string|number;treated:string|number;closed:string|number;avg_active_severity:string|number|null;active_area_ha:string|number};
type Envelope<T>={data:T};
const apiBase=(import.meta.env.VITE_API_URL as string|undefined)??'http://localhost:8787';
async function api<T>(path:string,init?:RequestInit):Promise<T>{const token=await getApiToken();if(!token)throw new Error('Sessão expirada.');const r=await fetch(`${apiBase}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers??{})}});const b=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(b.error??'api_error');return b as T;}

export function AgronomyPanel({farmId,seasonId,fields,role,section}:{farmId:string;seasonId:string;fields:Field[];role:string;section:'Solo'|'Pragas'}){
  const [samples,setSamples]=useState<SoilSample[]>([]),[soilSummary,setSoilSummary]=useState<SoilSummary|null>(null),[pests,setPests]=useState<Pest[]>([]),[pestSummary,setPestSummary]=useState<PestSummary|null>(null),[error,setError]=useState('');
  const canManage=['owner','admin','manager','agronomist'].includes(role),canExecute=['owner','admin','manager','agronomist','operator'].includes(role);
  async function load(){if(!farmId)return;setError('');try{if(section==='Solo'){const [a,b]=await Promise.all([api<Envelope<SoilSample[]>>(`/api/v1/soil/samples?farmId=${encodeURIComponent(farmId)}${seasonId?`&seasonId=${encodeURIComponent(seasonId)}`:''}`),api<Envelope<SoilSummary>>(`/api/v1/soil/summary?farmId=${encodeURIComponent(farmId)}${seasonId?`&seasonId=${encodeURIComponent(seasonId)}`:''}`)]);setSamples(a.data);setSoilSummary(b.data);}else{const [a,b]=await Promise.all([api<Envelope<Pest[]>>(`/api/v1/pests?farmId=${encodeURIComponent(farmId)}${seasonId?`&seasonId=${encodeURIComponent(seasonId)}`:''}`),api<Envelope<PestSummary>>(`/api/v1/pests/summary?farmId=${encodeURIComponent(farmId)}${seasonId?`&seasonId=${encodeURIComponent(seasonId)}`:''}`)]);setPests(a.data);setPestSummary(b.data);}}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar dados agronômicos.');}}
  useEffect(()=>{void load();},[farmId,seasonId,section]);
  return <div className="agroPage">{error&&<div className="errorBanner">{error}</div>}{section==='Solo'?<SoilView farmId={farmId} seasonId={seasonId} fields={fields} canManage={canManage} summary={soilSummary} samples={samples} reload={load}/>:<PestView farmId={farmId} seasonId={seasonId} fields={fields} canManage={canManage} canExecute={canExecute} summary={pestSummary} pests={pests} reload={load}/>}</div>;
}

function SoilView({farmId,seasonId,fields,canManage,summary,samples,reload}:{farmId:string;seasonId:string;fields:Field[];canManage:boolean;summary:SoilSummary|null;samples:SoilSample[];reload:()=>Promise<void>}){const [show,setShow]=useState(false);return <><div className="agroKpis"><AgroKpi label="AMOSTRAS" value={summary?.samples??0}/><AgroKpi label="TALHÕES AMOSTRADOS" value={summary?.sampled_fields??0}/><AgroKpi label="pH MÉDIO" value={formatNum(summary?.avg_ph,2)}/><AgroKpi label="V% MÉDIA" value={summary?.avg_base_saturation==null?'—':`${formatNum(summary.avg_base_saturation,1)}%`}/></div><div className="agroToolbar"><div><h2>Solo georreferenciado</h2><p>Histórico laboratorial por ponto, talhão e safra. O sistema exibe valores; faixas de interpretação serão configuráveis por região/laboratório.</p></div>{canManage&&<button onClick={()=>setShow(v=>!v)}>+ Amostra</button>}</div>{show&&<SoilForm farmId={farmId} seasonId={seasonId} fields={fields} onDone={async()=>{setShow(false);await reload();}}/>}<div className="panel agroTable"><div className="agroRow agroHead"><strong>AMOSTRA</strong><span>TALHÃO</span><span>DATA</span><span>pH</span><span>P</span><span>K</span><span>MO</span><span>V%</span></div>{samples.map(s=><div className="agroRow" key={s.id}><strong>{s.sample_code}</strong><span>{s.field_code}</span><span>{new Date(`${s.sampled_on}T12:00:00`).toLocaleDateString('pt-BR')}</span><span>{formatNum(s.ph,2)}</span><span>{formatNum(s.phosphorus_mg_dm3,1)}</span><span>{formatNum(s.potassium_mmolc_dm3,1)}</span><span>{formatNum(s.organic_matter_g_dm3,1)}</span><span>{s.base_saturation_pct==null?'—':`${formatNum(s.base_saturation_pct,1)}%`}</span></div>)}{!samples.length&&<div className="emptyState">Nenhuma amostra de solo registrada.</div>}</div></>}

function PestView({farmId,seasonId,fields,canManage,canExecute,summary,pests,reload}:{farmId:string;seasonId:string;fields:Field[];canManage:boolean;canExecute:boolean;summary:PestSummary|null;pests:Pest[];reload:()=>Promise<void>}){const [show,setShow]=useState(false),[busy,setBusy]=useState('');async function workOrder(id:string){setBusy(id);try{await api(`/api/v1/pests/${id}/work-order`,{method:'POST'});await reload();}finally{setBusy('')}}async function close(id:string,status:'monitoring'|'treated'|'closed'){setBusy(id);try{await api(`/api/v1/pests/${id}`,{method:'PATCH',body:JSON.stringify({status})});await reload();}finally{setBusy('')}}return <><div className="agroKpis"><AgroKpi label="OCORRÊNCIAS ATIVAS" value={summary?.active??0}/><AgroKpi label="SEVERIDADE 4–5" value={summary?.high_severity??0} warn={Number(summary?.high_severity??0)>0}/><AgroKpi label="ÁREA AFETADA" value={`${formatNum(summary?.active_area_ha,2)} ha`}/><AgroKpi label="TRATADAS" value={summary?.treated??0}/></div><div className="agroToolbar"><div><h2>Pragas, doenças e plantas daninhas</h2><p>Monitoramento por talhão com severidade, área afetada, ponto GPS e integração com Ordens de Serviço.</p></div>{canExecute&&<button onClick={()=>setShow(v=>!v)}>+ Ocorrência</button>}</div>{show&&<PestForm farmId={farmId} seasonId={seasonId} fields={fields} onDone={async()=>{setShow(false);await reload();}}/>}<div className="agroCards">{pests.map(p=><article className={`agroCard sev${p.severity}`} key={p.id}><div className="agroCardHead"><div><small>{labelCategory(p.category)} · {p.field_code}</small><h3>{p.name}</h3></div><span className="severity">S{p.severity}</span></div><p>{new Date(`${p.observed_on}T12:00:00`).toLocaleDateString('pt-BR')} · {p.infested_area_ha?`${formatNum(p.infested_area_ha,2)} ha`:p.infestation_pct?`${formatNum(p.infestation_pct,1)}%`:'área não informada'}</p><div className="agroTags"><span>{labelStatus(p.status)}</span><span>{p.action_count} ação(ões)</span></div>{p.notes&&<p className="agroNote">{p.notes}</p>}<div className="agroActions">{canManage&&p.status!=='closed'&&<button disabled={busy===p.id} onClick={()=>workOrder(p.id)}>Gerar OS</button>}{canManage&&p.status==='open'&&<button disabled={busy===p.id} onClick={()=>close(p.id,'monitoring')}>Monitorar</button>}{canManage&&p.status!=='closed'&&<button disabled={busy===p.id} onClick={()=>close(p.id,'closed')}>Encerrar</button>}</div></article>)}{!pests.length&&<div className="emptyState">Nenhuma ocorrência registrada para a seleção atual.</div>}</div></>}

function SoilForm({farmId,seasonId,fields,onDone}:{farmId:string;seasonId:string;fields:Field[];onDone:()=>Promise<void>}){const [fieldId,setFieldId]=useState(fields[0]?.id??''),[code,setCode]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[ph,setPh]=useState(''),[om,setOm]=useState(''),[p,setP]=useState(''),[k,setK]=useState(''),[v,setV]=useState(''),[pos,setPos]=useState<{latitude:number;longitude:number}|undefined>();useEffect(()=>{if(!fieldId&&fields[0])setFieldId(fields[0].id)},[fields]);function gps(){navigator.geolocation?.getCurrentPosition(x=>setPos({latitude:x.coords.latitude,longitude:x.coords.longitude}))}return <form className="agroForm" onSubmit={async e=>{e.preventDefault();await api('/api/v1/soil/samples',{method:'POST',body:JSON.stringify({farmId,fieldId,seasonId:seasonId||undefined,sampleCode:code,sampledOn:date,ph:ph?Number(ph):undefined,organicMatterGdm3:om?Number(om):undefined,phosphorusMgdm3:p?Number(p):undefined,potassiumMmolcDm3:k?Number(k):undefined,baseSaturationPct:v?Number(v):undefined,location:pos})});await onDone();}}><strong>Nova amostra de solo</strong><select value={fieldId} onChange={e=>setFieldId(e.target.value)} required>{fields.map(f=><option key={f.id} value={f.id}>{f.code}</option>)}</select><input placeholder="Código da amostra" value={code} onChange={e=>setCode(e.target.value)} required/><input type="date" value={date} onChange={e=>setDate(e.target.value)} required/><input type="number" step="0.01" placeholder="pH" value={ph} onChange={e=>setPh(e.target.value)}/><input type="number" step="0.001" placeholder="MO g/dm³" value={om} onChange={e=>setOm(e.target.value)}/><input type="number" step="0.001" placeholder="P mg/dm³" value={p} onChange={e=>setP(e.target.value)}/><input type="number" step="0.001" placeholder="K mmolc/dm³" value={k} onChange={e=>setK(e.target.value)}/><input type="number" step="0.01" placeholder="V%" value={v} onChange={e=>setV(e.target.value)}/><button type="button" className="secondaryAgro" onClick={gps}>{pos?'GPS capturado':'Capturar GPS'}</button><button>Salvar amostra</button></form>}

function PestForm({farmId,seasonId,fields,onDone}:{farmId:string;seasonId:string;fields:Field[];onDone:()=>Promise<void>}){const [fieldId,setFieldId]=useState(fields[0]?.id??''),[category,setCategory]=useState('pest'),[name,setName]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[severity,setSeverity]=useState('3'),[pct,setPct]=useState(''),[area,setArea]=useState(''),[notes,setNotes]=useState(''),[pos,setPos]=useState<{latitude:number;longitude:number}|undefined>();useEffect(()=>{if(!fieldId&&fields[0])setFieldId(fields[0].id)},[fields]);function gps(){navigator.geolocation?.getCurrentPosition(x=>setPos({latitude:x.coords.latitude,longitude:x.coords.longitude}))}return <form className="agroForm" onSubmit={async e=>{e.preventDefault();await api('/api/v1/pests',{method:'POST',body:JSON.stringify({farmId,fieldId,seasonId:seasonId||undefined,category,name,observedOn:date,severity:Number(severity),infestationPct:pct?Number(pct):undefined,infestedAreaHa:area?Number(area):undefined,notes:notes||undefined,location:pos})});await onDone();}}><strong>Nova ocorrência</strong><select value={fieldId} onChange={e=>setFieldId(e.target.value)} required>{fields.map(f=><option key={f.id} value={f.id}>{f.code}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="pest">Praga</option><option value="disease">Doença</option><option value="weed">Planta daninha</option><option value="other">Outro</option></select><input placeholder="Nome / agente" value={name} onChange={e=>setName(e.target.value)} required/><input type="date" value={date} onChange={e=>setDate(e.target.value)} required/><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="1">Severidade 1</option><option value="2">Severidade 2</option><option value="3">Severidade 3</option><option value="4">Severidade 4</option><option value="5">Severidade 5</option></select><input type="number" min="0" max="100" step="0.1" placeholder="Infestação %" value={pct} onChange={e=>setPct(e.target.value)}/><input type="number" min="0" step="0.01" placeholder="Área afetada ha" value={area} onChange={e=>setArea(e.target.value)}/><input placeholder="Observações" value={notes} onChange={e=>setNotes(e.target.value)}/><button type="button" className="secondaryAgro" onClick={gps}>{pos?'GPS capturado':'Capturar GPS'}</button><button>Registrar ocorrência</button></form>}

function AgroKpi({label,value,warn=false}:{label:string;value:string|number;warn?:boolean}){return <div className="agroKpi"><small>{label}</small><strong className={warn?'warning':''}>{value}</strong></div>}
function formatNum(v:string|number|null|undefined,d=1){return v==null?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:d,minimumFractionDigits:0})}
function labelCategory(v:string){return({pest:'Praga',disease:'Doença',weed:'Planta daninha',other:'Outro'} as Record<string,string>)[v]??v}
function labelStatus(v:string){return({open:'Aberta',monitoring:'Monitoramento',treated:'Tratada',closed:'Encerrada'} as Record<string,string>)[v]??v}
