import { useEffect, useMemo, useState } from 'react';
import { getApiToken } from './auth';

type Field={id:string;code:string};
type Machine={id:string;code:string;name:string;machine_type:string;brand:string|null;model:string|null;status:string;hour_meter:string|number|null;hourly_cost:string|number|null;next_maintenance_hours:string|number|null;maintenance_due:boolean};
type Usage={id:string;machine_name:string;machine_code:string;usage_type:string;field_code:string|null;actual_cost:string|number|null;fuel_liters:string|number|null;start_hour_meter:string|number|null;end_hour_meter:string|number|null;created_at:string};
type Item={id:string;sku:string|null;name:string;category:string;unit:string;current_quantity:string|number;minimum_quantity:string|number;average_unit_cost:string|number;low_stock:boolean};
type Movement={id:string;item_name:string;unit:string;movement_type:string;quantity:string|number;unit_cost:string|number|null;field_code:string|null;occurred_at:string};
type Summary={active_machines:string|number;maintenance_machines:string|number;maintenance_due:string|number;inventory_items:string|number;low_stock_items:string|number;inventory_value:string|number;machine_cost:string|number;fuel_liters:string|number};
type Envelope<T>={data:T};

const apiBase=(import.meta.env.VITE_API_URL as string|undefined)??'http://localhost:8787';
async function api<T>(path:string,init?:RequestInit):Promise<T>{const token=await getApiToken();if(!token)throw new Error('Sessão expirada.');const r=await fetch(`${apiBase}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers??{})}});const b=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(b.error??'api_error');return b as T;}

export function AssetsPanel({farmId,seasonId,fields,role,section}:{farmId:string;seasonId:string;fields:Field[];role:string;section:'Máquinas'|'Estoque'}){
  const [machines,setMachines]=useState<Machine[]>([]),[usages,setUsages]=useState<Usage[]>([]),[items,setItems]=useState<Item[]>([]),[movements,setMovements]=useState<Movement[]>([]),[summary,setSummary]=useState<Summary|null>(null),[error,setError]=useState('');
  const canManage=['owner','admin','manager'].includes(role),canExecute=['owner','admin','manager','agronomist','operator'].includes(role);
  async function load(){if(!farmId||!seasonId)return;setError('');try{const [m,u,i,mv,s]=await Promise.all([api<Envelope<Machine[]>>(`/api/v1/machines?farmId=${encodeURIComponent(farmId)}`),api<Envelope<Usage[]>>(`/api/v1/machine-usages?seasonId=${encodeURIComponent(seasonId)}`),api<Envelope<Item[]>>('/api/v1/inventory/items'),api<Envelope<Movement[]>>(`/api/v1/inventory/movements?seasonId=${encodeURIComponent(seasonId)}`),api<Envelope<Summary>>(`/api/v1/assets/summary?farmId=${encodeURIComponent(farmId)}&seasonId=${encodeURIComponent(seasonId)}`)]);setMachines(m.data);setUsages(u.data);setItems(i.data);setMovements(mv.data);setSummary(s.data);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar ativos.');}}
  useEffect(()=>{void load();},[farmId,seasonId]);
  return <div className="assetPage">{error&&<div className="errorBanner">{error}</div>}<div className="assetKpis"><AssetKpi label="MÁQUINAS ATIVAS" value={summary?.active_machines??0}/><AssetKpi label="MANUTENÇÃO" value={summary?.maintenance_machines??0} warn={Number(summary?.maintenance_due??0)>0}/><AssetKpi label="ESTOQUE BAIXO" value={summary?.low_stock_items??0} warn={Number(summary?.low_stock_items??0)>0}/><AssetKpi label="VALOR ESTOQUE" value={`R$ ${Number(summary?.inventory_value??0).toLocaleString('pt-BR',{maximumFractionDigits:0})}`}/></div>{section==='Máquinas'?<MachinesView machines={machines} usages={usages} farmId={farmId} seasonId={seasonId} fields={fields} canManage={canManage} canExecute={canExecute} reload={load}/>:<InventoryView items={items} movements={movements} seasonId={seasonId} fields={fields} canManage={canManage} canExecute={canExecute} reload={load}/>}</div>;
}

function MachinesView({machines,usages,farmId,seasonId,fields,canManage,canExecute,reload}:{machines:Machine[];usages:Usage[];farmId:string;seasonId:string;fields:Field[];canManage:boolean;canExecute:boolean;reload:()=>Promise<void>}){
  const [showMachine,setShowMachine]=useState(false),[showUsage,setShowUsage]=useState(false);
  const due=machines.filter(m=>m.maintenance_due||m.status==='maintenance');
  return <><div className="assetToolbar"><div><h2>Máquinas e implementos</h2><p>Horímetro, custo operacional, combustível e manutenção.</p></div><div>{canManage&&<button onClick={()=>setShowMachine(v=>!v)}>+ Máquina</button>}{canExecute&&<button onClick={()=>setShowUsage(v=>!v)}>+ Apontamento</button>}</div></div>{showMachine&&<MachineForm farmId={farmId} onDone={async()=>{setShowMachine(false);await reload();}}/>}{showUsage&&<UsageForm machines={machines} fields={fields} seasonId={seasonId} onDone={async()=>{setShowUsage(false);await reload();}}/>}{due.length>0&&<div className="assetAlert"><strong>{due.length} máquina(s) exigem atenção</strong><span>Manutenção programada atingida ou status em manutenção.</span></div>}<div className="assetGrid">{machines.map(m=><div className="assetCard" key={m.id}><div className="assetCardHead"><strong>{m.code} · {m.name}</strong><span className={`assetStatus ${m.status}`}>{m.status}</span></div><p>{m.machine_type}{m.brand?` · ${m.brand}`:''}{m.model?` ${m.model}`:''}</p><div className="assetMetrics"><span><small>HORÍMETRO</small>{Number(m.hour_meter??0).toLocaleString('pt-BR')} h</span><span><small>CUSTO/H</small>R$ {Number(m.hourly_cost??0).toLocaleString('pt-BR',{maximumFractionDigits:2})}</span><span><small>PRÓX. MANUT.</small>{m.next_maintenance_hours?`${Number(m.next_maintenance_hours).toLocaleString('pt-BR')} h`:'—'}</span></div></div>)}{!machines.length&&<div className="emptyState">Nenhuma máquina cadastrada.</div>}</div><div className="panel assetTable"><div className="panelTitle"><span>APONTAMENTOS RECENTES</span><small>custos alimentam o Financeiro</small></div>{usages.slice(0,20).map(u=><div className="assetRow" key={u.id}><strong>{u.machine_code} · {u.machine_name}</strong><span>{labelUsage(u.usage_type)}</span><span>{u.field_code??'Geral'}</span><span>{u.fuel_liters?`${Number(u.fuel_liters).toLocaleString('pt-BR')} L`:'—'}</span><span>R$ {Number(u.actual_cost??0).toLocaleString('pt-BR',{maximumFractionDigits:2})}</span></div>)}</div></>;
}

function InventoryView({items,movements,seasonId,fields,canManage,canExecute,reload}:{items:Item[];movements:Movement[];seasonId:string;fields:Field[];canManage:boolean;canExecute:boolean;reload:()=>Promise<void>}){
  const [showItem,setShowItem]=useState(false),[showMove,setShowMove]=useState(false);const low=useMemo(()=>items.filter(i=>i.low_stock),[items]);
  return <><div className="assetToolbar"><div><h2>Estoque de insumos</h2><p>Saldo, custo médio, estoque mínimo e consumo por talhão.</p></div><div>{canManage&&<button onClick={()=>setShowItem(v=>!v)}>+ Item</button>}{canExecute&&<button onClick={()=>setShowMove(v=>!v)}>+ Movimento</button>}</div></div>{showItem&&<ItemForm onDone={async()=>{setShowItem(false);await reload();}}/>}{showMove&&<MovementForm items={items} fields={fields} seasonId={seasonId} onDone={async()=>{setShowMove(false);await reload();}}/>}{low.length>0&&<div className="assetAlert"><strong>{low.length} item(ns) no mínimo ou abaixo</strong><span>Priorize reposição antes das próximas operações.</span></div>}<div className="panel assetTable"><div className="assetRow assetHead"><strong>ITEM</strong><span>CATEGORIA</span><span>SALDO</span><span>MÍNIMO</span><span>CUSTO MÉDIO</span></div>{items.map(i=><div className={`assetRow ${i.low_stock?'lowStock':''}`} key={i.id}><strong>{i.sku?`${i.sku} · `:''}{i.name}</strong><span>{i.category}</span><span>{Number(i.current_quantity).toLocaleString('pt-BR')} {i.unit}</span><span>{Number(i.minimum_quantity).toLocaleString('pt-BR')} {i.unit}</span><span>R$ {Number(i.average_unit_cost).toLocaleString('pt-BR',{maximumFractionDigits:4})}</span></div>)}{!items.length&&<div className="emptyState">Nenhum item de estoque cadastrado.</div>}</div><div className="panel assetTable"><div className="panelTitle"><span>MOVIMENTAÇÕES</span><small>saídas podem gerar custo agrícola</small></div>{movements.slice(0,30).map(m=><div className="assetRow" key={m.id}><strong>{m.item_name}</strong><span>{labelMovement(m.movement_type)}</span><span>{Number(m.quantity).toLocaleString('pt-BR')} {m.unit}</span><span>{m.field_code??'Geral'}</span><span>{new Date(m.occurred_at).toLocaleDateString('pt-BR')}</span></div>)}</div></>;
}

function MachineForm({farmId,onDone}:{farmId:string;onDone:()=>Promise<void>}){const [code,setCode]=useState(''),[name,setName]=useState(''),[type,setType]=useState('Trator'),[hourly,setHourly]=useState(''),[meter,setMeter]=useState('');return <form className="assetForm" onSubmit={async e=>{e.preventDefault();await api('/api/v1/machines',{method:'POST',body:JSON.stringify({farmId,code,name,machineType:type,hourlyCost:hourly?Number(hourly):undefined,hourMeter:meter?Number(meter):undefined})});await onDone();}}><strong>Nova máquina</strong><input placeholder="Código" value={code} onChange={e=>setCode(e.target.value)} required/><input placeholder="Nome" value={name} onChange={e=>setName(e.target.value)} required/><input placeholder="Tipo" value={type} onChange={e=>setType(e.target.value)} required/><input type="number" step="0.01" placeholder="Custo/h" value={hourly} onChange={e=>setHourly(e.target.value)}/><input type="number" step="0.01" placeholder="Horímetro atual" value={meter} onChange={e=>setMeter(e.target.value)}/><button>Salvar</button></form>}
function UsageForm({machines,fields,seasonId,onDone}:{machines:Machine[];fields:Field[];seasonId:string;onDone:()=>Promise<void>}){const [machineId,setMachineId]=useState(machines[0]?.id??''),[fieldId,setFieldId]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[fuel,setFuel]=useState(''),[fuelCost,setFuelCost]=useState('');useEffect(()=>{if(!machineId&&machines[0])setMachineId(machines[0].id)},[machines]);return <form className="assetForm" onSubmit={async e=>{e.preventDefault();await api('/api/v1/machine-usages',{method:'POST',body:JSON.stringify({machineId,seasonId,fieldId:fieldId||undefined,startHourMeter:start?Number(start):undefined,endHourMeter:end?Number(end):undefined,fuelLiters:fuel?Number(fuel):undefined,fuelUnitCost:fuelCost?Number(fuelCost):undefined})});await onDone();}}><strong>Novo apontamento</strong><select value={machineId} onChange={e=>setMachineId(e.target.value)} required>{machines.map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select><select value={fieldId} onChange={e=>setFieldId(e.target.value)}><option value="">Sem talhão</option>{fields.map(f=><option key={f.id} value={f.id}>{f.code}</option>)}</select><input type="number" step="0.01" placeholder="Horímetro inicial" value={start} onChange={e=>setStart(e.target.value)}/><input type="number" step="0.01" placeholder="Horímetro final" value={end} onChange={e=>setEnd(e.target.value)}/><input type="number" step="0.001" placeholder="Combustível (L)" value={fuel} onChange={e=>setFuel(e.target.value)}/><input type="number" step="0.0001" placeholder="R$/L" value={fuelCost} onChange={e=>setFuelCost(e.target.value)}/><button>Registrar</button></form>}
function ItemForm({onDone}:{onDone:()=>Promise<void>}){const [sku,setSku]=useState(''),[name,setName]=useState(''),[category,setCategory]=useState('Defensivos'),[unit,setUnit]=useState('L'),[min,setMin]=useState('0'),[cost,setCost]=useState('0');return <form className="assetForm" onSubmit={async e=>{e.preventDefault();await api('/api/v1/inventory/items',{method:'POST',body:JSON.stringify({sku:sku||undefined,name,category,unit,minimumQuantity:Number(min),averageUnitCost:Number(cost)})});await onDone();}}><strong>Novo item</strong><input placeholder="SKU" value={sku} onChange={e=>setSku(e.target.value)}/><input placeholder="Nome" value={name} onChange={e=>setName(e.target.value)} required/><input placeholder="Categoria" value={category} onChange={e=>setCategory(e.target.value)} required/><input placeholder="Unidade" value={unit} onChange={e=>setUnit(e.target.value)} required/><input type="number" step="0.0001" placeholder="Estoque mínimo" value={min} onChange={e=>setMin(e.target.value)}/><input type="number" step="0.0001" placeholder="Custo médio inicial" value={cost} onChange={e=>setCost(e.target.value)}/><button>Salvar</button></form>}
function MovementForm({items,fields,seasonId,onDone}:{items:Item[];fields:Field[];seasonId:string;onDone:()=>Promise<void>}){const [itemId,setItemId]=useState(items[0]?.id??''),[type,setType]=useState('in'),[qty,setQty]=useState(''),[unitCost,setUnitCost]=useState(''),[fieldId,setFieldId]=useState('');useEffect(()=>{if(!itemId&&items[0])setItemId(items[0].id)},[items]);return <form className="assetForm" onSubmit={async e=>{e.preventDefault();await api('/api/v1/inventory/movements',{method:'POST',body:JSON.stringify({inventoryItemId:itemId,movementType:type,quantity:Number(qty),unitCost:unitCost?Number(unitCost):undefined,seasonId:type.includes('out')?seasonId:undefined,fieldId:type.includes('out')&&fieldId?fieldId:undefined})});await onDone();}}><strong>Movimentação</strong><select value={itemId} onChange={e=>setItemId(e.target.value)} required>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {Number(i.current_quantity).toLocaleString('pt-BR')} {i.unit}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="in">Entrada</option><option value="out">Saída/consumo</option><option value="adjustment_in">Ajuste +</option><option value="adjustment_out">Ajuste -</option></select><input type="number" min="0.0001" step="0.0001" placeholder="Quantidade" value={qty} onChange={e=>setQty(e.target.value)} required/><input type="number" min="0" step="0.0001" placeholder="Custo unitário" value={unitCost} onChange={e=>setUnitCost(e.target.value)}/><select value={fieldId} onChange={e=>setFieldId(e.target.value)}><option value="">Sem talhão</option>{fields.map(f=><option key={f.id} value={f.id}>{f.code}</option>)}</select><button>Registrar</button></form>}
function AssetKpi({label,value,warn=false}:{label:string;value:string|number;warn?:boolean}){return <div className="assetKpi"><small>{label}</small><strong className={warn?'warning':''}>{value}</strong></div>}
function labelUsage(v:string){return ({operation:'Operação',maintenance:'Manutenção',fuel:'Abastecimento',breakdown:'Quebra'} as Record<string,string>)[v]??v}
function labelMovement(v:string){return ({in:'Entrada',out:'Saída',adjustment_in:'Ajuste +',adjustment_out:'Ajuste -'} as Record<string,string>)[v]??v}
