import { useEffect, useState } from 'react';
import { getApiToken } from './auth';

type Field={id:string;code:string;area_ha:string|number|null;variety:string|null};
type Props={farmId:string;seasonId:string;fields:Field[];section:'Simulador'|'IA agronômica'};
type Envelope<T>={data:T};
const apiBase=(import.meta.env.VITE_API_URL as string|undefined)??'http://localhost:8787';
async function api<T>(path:string,init?:RequestInit):Promise<T>{const token=await getApiToken();if(!token)throw new Error('Sessão expirada.');const r=await fetch(`${apiBase}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers??{})}});const body=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(body.error??'api_error');return body as T;}
const money=(v:unknown)=>Number(v??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const num=(v:unknown,d=1)=>Number(v??0).toLocaleString('pt-BR',{maximumFractionDigits:d});

type SimResult={grossTons:number;netTons:number;atrMassKg:number;revenue:number;variableCost:number;totalCost:number;margin:number;marginPerHa:number;revenuePerHa:number;marginPct:number|null;breakEvenTch:number|null;breakEvenAtrKgT:number|null};
type EconomicRow={field_id:string;tch:string|number|null;atr_kg_t:string|number|null;cost_per_ha:string|number|null};
type Plan={field_id:string;expected_tch:string|number|null;expected_atr:string|number|null};
type AiResponse={provider:string;answer:string;context:{field:unknown;production:unknown;soil:unknown[];pests:unknown[];weather:unknown[];vegetation:unknown[];operations:unknown[];harvest:unknown[]}};

export function DecisionSupportPanel(props:Props){return props.section==='Simulador'?<Simulator {...props}/>:<AgronomyAi {...props}/>;}

function Simulator({farmId,seasonId,fields}:Props){
  const [fieldId,setFieldId]=useState('');const [area,setArea]=useState('');const [tch,setTch]=useState('');const [atr,setAtr]=useState('');const [price,setPrice]=useState('');const [costHa,setCostHa]=useState('');const [fixed,setFixed]=useState('0');const [lease,setLease]=useState('0');const [loss,setLoss]=useState('0');const [result,setResult]=useState<SimResult|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!fieldId&&fields[0])setFieldId(fields[0].id);},[fields,fieldId]);
  useEffect(()=>{const f=fields.find(x=>x.id===fieldId);if(!f)return;setArea(String(f.area_ha??''));if(!seasonId)return;Promise.all([api<Envelope<EconomicRow[]>>(`/api/v1/economics/fields?seasonId=${encodeURIComponent(seasonId)}&farmId=${encodeURIComponent(farmId)}`),api<Envelope<Plan[]>>(`/api/v1/planning?seasonId=${encodeURIComponent(seasonId)}&farmId=${encodeURIComponent(farmId)}`)]).then(([e,p])=>{const er=e.data.find(x=>x.field_id===fieldId);const pl=p.data.find(x=>x.field_id===fieldId);setTch(String(er?.tch??pl?.expected_tch??''));setAtr(String(er?.atr_kg_t??pl?.expected_atr??''));setCostHa(String(er?.cost_per_ha??''));}).catch(()=>{});},[fieldId,seasonId,farmId]);
  async function run(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<Envelope<SimResult>>('/api/v1/simulator',{method:'POST',body:JSON.stringify({areaHa:Number(area),tch:Number(tch),atrKgT:Number(atr),atrPricePerKg:Number(price),costPerHa:Number(costHa),fixedCosts:Number(fixed||0),leaseCost:Number(lease||0),harvestLossPct:Number(loss||0)})});setResult(r.data);}catch(c){setError(c instanceof Error?c.message:'Falha ao simular.');}finally{setBusy(false);}}
  return <div className="dsWorkspace"><div className="notice">Simulação determinística: nenhum valor é gravado no banco. Ajuste produtividade, ATR, preço e custos para testar cenários.</div>{error&&<div className="errorBanner">{error}</div>}<div className="dsGrid"><form className="panel dsForm" onSubmit={run}><div className="panelTitle"><span>CENÁRIO</span><small>Talhão + premissas</small></div><label>Talhão<select value={fieldId} onChange={e=>setFieldId(e.target.value)}>{fields.map(f=><option key={f.id} value={f.id}>{f.code} · {f.variety??'—'}</option>)}</select></label><label>Área (ha)<input type="number" step="0.01" min="0.01" required value={area} onChange={e=>setArea(e.target.value)}/></label><label>TCH<input type="number" step="0.01" min="0" required value={tch} onChange={e=>setTch(e.target.value)}/></label><label>ATR (kg/t)<input type="number" step="0.01" min="0" required value={atr} onChange={e=>setAtr(e.target.value)}/></label><label>R$/kg ATR<input type="number" step="0.0001" min="0" required value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Custo/ha<input type="number" step="0.01" min="0" required value={costHa} onChange={e=>setCostHa(e.target.value)}/></label><label>Custos fixos<input type="number" step="0.01" min="0" value={fixed} onChange={e=>setFixed(e.target.value)}/></label><label>Arrendamento<input type="number" step="0.01" min="0" value={lease} onChange={e=>setLease(e.target.value)}/></label><label>Perda colheita (%)<input type="number" step="0.1" min="0" max="100" value={loss} onChange={e=>setLoss(e.target.value)}/></label><button className="primaryButton" disabled={busy}>{busy?'Calculando…':'Simular cenário'}</button></form><section className="panel"><div className="panelTitle"><span>RESULTADO</span><small>projeção financeira</small></div>{result?<div className="dsResults"><Result label="TONELADAS LÍQUIDAS" value={`${num(result.netTons,1)} t`}/><Result label="RECEITA" value={money(result.revenue)}/><Result label="CUSTO TOTAL" value={money(result.totalCost)}/><Result label="MARGEM" value={money(result.margin)} warn={result.margin<0}/><Result label="MARGEM/HA" value={money(result.marginPerHa)} warn={result.marginPerHa<0}/><Result label="MARGEM %" value={result.marginPct==null?'—':`${num(result.marginPct,1)}%`} warn={Number(result.marginPct??0)<0}/><Result label="TCH EQUILÍBRIO" value={result.breakEvenTch==null?'—':`${num(result.breakEvenTch,1)} t/ha`}/><Result label="ATR EQUILÍBRIO" value={result.breakEvenAtrKgT==null?'—':`${num(result.breakEvenAtrKgT,1)} kg/t`}/></div>:<div className="emptyState">Informe as premissas e execute a simulação.</div>}</section></div></div>;
}

function AgronomyAi({seasonId,fields}:Props){
  const [fieldId,setFieldId]=useState('');const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');const [provider,setProvider]=useState('');const [sources,setSources]=useState<Record<string,number>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{if(!fieldId&&fields[0])setFieldId(fields[0].id);},[fields,fieldId]);
  async function ask(e:React.FormEvent){e.preventDefault();if(!fieldId||!seasonId)return;setBusy(true);setError('');setAnswer('');try{const r=await api<AiResponse>('/api/v1/ai/agronomy',{method:'POST',body:JSON.stringify({fieldId,seasonId,question})});setAnswer(r.answer);setProvider(r.provider);setSources({solo:r.context.soil.length,pragas:r.context.pests.length,clima:r.context.weather.length,satelite:r.context.vegetation.length,operacoes:r.context.operations.length,colheita:r.context.harvest.length});}catch(c){setError(c instanceof Error?c.message:'Falha ao consultar IA.');}finally{setBusy(false);}}
  return <div className="dsWorkspace"><div className="notice">A IA consulta o banco autorizado do talhão/safra. Ela não deve inventar dados e não substitui validação de engenheiro agrônomo ou responsável técnico.</div>{error&&<div className="errorBanner">{error}</div>}<div className="dsGrid"><form className="panel dsAiForm" onSubmit={ask}><div className="panelTitle"><span>PERGUNTA AGRONÔMICA</span><small>contexto real</small></div><label>Talhão<select value={fieldId} onChange={e=>setFieldId(e.target.value)}>{fields.map(f=><option key={f.id} value={f.id}>{f.code} · {f.variety??'—'}</option>)}</select></label><label>Pergunta<textarea required minLength={3} maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ex.: quais são os principais riscos deste talhão para as próximas operações?"/></label><button className="primaryButton" disabled={busy||!fieldId}>{busy?'Analisando…':'Analisar com IA'}</button><small>A resposta considera planejamento, produção/custos, solo, pragas, clima, satélite, OS e colheita quando esses dados existirem.</small></form><section className="panel dsAnswer"><div className="panelTitle"><span>ANÁLISE</span><small>{provider||'aguardando'}</small></div>{answer?<><div className="dsAnswerText">{answer}</div><div className="dsSources">{Object.entries(sources).map(([k,v])=><span key={k}>{k}: <strong>{v}</strong></span>)}</div></>:<div className="emptyState">Faça uma pergunta para gerar a análise contextual.</div>}</section></div></div>;
}

function Result({label,value,warn=false}:{label:string;value:string;warn?:boolean}){return <div className="dsResult"><small>{label}</small><strong className={warn?'warning':''}>{value}</strong></div>}
