import { useEffect, useMemo, useState } from 'react';
import { getApiToken } from './auth';

type Field={id:string;code:string;area_ha:string|number|null};
type Props={farmId:string;seasonId:string;fields:Field[];role:string;section:'Financeiro'|'Produção'};
type Envelope<T>={data:T};
const apiBase=(import.meta.env.VITE_API_URL as string|undefined)??'http://localhost:8787';
async function api<T>(path:string,init?:RequestInit):Promise<T>{const token=await getApiToken();if(!token)throw new Error('Sessão expirada.');const r=await fetch(`${apiBase}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers??{})}});const body=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(body.error??'api_error');return body as T;}
const money=(v:unknown)=>Number(v??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const num=(v:unknown,d=1)=>Number(v??0).toLocaleString('pt-BR',{maximumFractionDigits:d});
const localDate=()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const productionRoles=new Set(['owner','admin','manager','agronomist','operator']);
const financeRoles=new Set(['owner','admin','manager']);

type EconRow={field_id:string;code:string;area_ha:string|number|null;variety:string|null;tons:string|number;atr_kg_t:string|number|null;tch:string|number|null;tah:string|number|null;revenue:string|number;cost:string|number;margin:string|number;cost_per_ha:string|number|null;margin_per_ha:string|number|null};
type EconSummary={area_ha:string|number;tons:string|number;atr_kg_t:string|number|null;revenue:string|number;total_cost:string|number;margin:string|number;tch:number|null;margin_per_ha:number|null;unallocated_cost:string|number};
type Production={id:string;field_id:string;field_code:string;occurred_on:string;tons:string|number;atr_kg_t:string|number|null;atr_price_per_kg:string|number|null;revenue_amount:string|number|null;calculated_revenue:string|number|null;source:string};
type Cost={id:string;field_id:string|null;field_code:string|null;category:string;occurred_on:string;amount:string|number;supplier:string|null};

export function EconomicsEmbeddedPanel({farmId,seasonId,fields,role,section}:Props){
  const [rows,setRows]=useState<EconRow[]>([]);const [summary,setSummary]=useState<EconSummary|null>(null);const [production,setProduction]=useState<Production[]>([]);const [costs,setCosts]=useState<Cost[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  async function load(){if(!seasonId)return;setLoading(true);setError('');try{const suffix=`seasonId=${encodeURIComponent(seasonId)}${farmId?`&farmId=${encodeURIComponent(farmId)}`:''}`;const [er,sr]=await Promise.all([api<Envelope<EconRow[]>>(`/api/v1/economics/fields?${suffix}`),api<Envelope<EconSummary>>(`/api/v1/economics/summary?${suffix}`)]);setRows(er.data);setSummary(sr.data);if(section==='Produção'){const r=await api<Envelope<Production[]>>(`/api/v1/production?seasonId=${encodeURIComponent(seasonId)}`);setProduction(r.data);}else{const r=await api<Envelope<Cost[]>>(`/api/v1/costs?seasonId=${encodeURIComponent(seasonId)}`);setCosts(r.data);}}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar módulo econômico.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[farmId,seasonId,section]);
  const best=useMemo(()=>rows.find(r=>Number(r.margin_per_ha??0)>0)??rows[0]??null,[rows]);
  return <div className="ecWorkspace"><section className="ecKpis"><Card label="TCH" value={`${num(summary?.tch,1)} t/ha`}/><Card label="ATR MÉDIO" value={summary?.atr_kg_t==null?'—':`${num(summary.atr_kg_t,1)} kg/t`}/><Card label="RECEITA" value={money(summary?.revenue)}/><Card label="MARGEM/HA" value={money(summary?.margin_per_ha)} warn={Number(summary?.margin_per_ha??0)<0}/></section>{error&&<div className="errorBanner">{error}</div>}<div className="ecTopbar"><span>{section==='Produção'?'Lançamentos e desempenho da safra':'Custos e rentabilidade da safra'}</span><button className="secondaryButton" onClick={()=>void load()} disabled={loading}>{loading?'Atualizando…':'Atualizar'}</button></div><section className="panel"><div className="panelTitle"><span>RANKING ECONÔMICO POR TALHÃO</span><small>{best?`melhor margem: ${best.code}`:'sem dados'}</small></div><div className="ecTableWrap"><table className="ecTable"><thead><tr><th>Talhão</th><th>ha</th><th>t</th><th>TCH</th><th>ATR</th><th>TAH</th><th>Receita</th><th>Custo/ha</th><th>Margem/ha</th></tr></thead><tbody>{rows.map(r=><tr key={r.field_id}><td><strong>{r.code}</strong><small>{r.variety??'—'}</small></td><td>{num(r.area_ha)}</td><td>{num(r.tons,0)}</td><td>{r.tch==null?'—':num(r.tch)}</td><td>{r.atr_kg_t==null?'—':num(r.atr_kg_t)}</td><td>{r.tah==null?'—':num(r.tah,2)}</td><td>{money(r.revenue)}</td><td>{money(r.cost_per_ha)}</td><td className={Number(r.margin_per_ha??0)<0?'negative':'positive'}>{money(r.margin_per_ha)}</td></tr>)}{!rows.length&&<tr><td colSpan={9}>Nenhum talhão disponível.</td></tr>}</tbody></table></div></section>{section==='Produção'?<ProductionSection fields={fields} seasonId={seasonId} role={role} records={production} onSaved={load}/>:<FinanceSection fields={fields} seasonId={seasonId} role={role} records={costs} summary={summary} onSaved={load}/>}</div>;
}

function ProductionSection({fields,seasonId,role,records,onSaved}:{fields:Field[];seasonId:string;role:string;records:Production[];onSaved:()=>Promise<void>}){const can=productionRoles.has(role);const [fieldId,setFieldId]=useState('');const [date,setDate]=useState(localDate());const [tons,setTons]=useState('');const [atr,setAtr]=useState('');const [price,setPrice]=useState('');const [revenue,setRevenue]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');useEffect(()=>{if(!fieldId&&fields[0])setFieldId(fields[0].id)},[fields,fieldId]);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/v1/production',{method:'POST',body:JSON.stringify({fieldId,seasonId,occurredOn:date,tons:Number(tons),atrKgT:atr?Number(atr):undefined,atrPricePerKg:price?Number(price):undefined,revenueAmount:revenue?Number(revenue):undefined,source:'manual'})});setTons('');setAtr('');setPrice('');setRevenue('');await onSaved();}catch(e){setError(e instanceof Error?e.message:'Falha ao lançar produção.');}finally{setBusy(false);}}return <div className="ecGrid">{can&&<form className="panel ecForm" onSubmit={submit}><div className="panelTitle"><span>LANÇAR PRODUÇÃO</span><small>manual</small></div><label>Talhão<select value={fieldId} onChange={e=>setFieldId(e.target.value)}>{fields.map(f=><option key={f.id} value={f.id}>{f.code}</option>)}</select></label><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Toneladas<input type="number" min="0.001" step="0.001" value={tons} onChange={e=>setTons(e.target.value)} required/></label><label>ATR kg/t<input type="number" min="0" step="0.01" value={atr} onChange={e=>setAtr(e.target.value)}/></label><label>R$/kg ATR<input type="number" min="0" step="0.0001" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Receita real<input type="number" min="0" step="0.01" value={revenue} onChange={e=>setRevenue(e.target.value)}/></label>{error&&<div className="formError">{error}</div>}<button className="primaryButton" disabled={busy}>{busy?'Salvando…':'Salvar produção'}</button></form>}<section className="panel"><div className="panelTitle"><span>ÚLTIMOS LANÇAMENTOS</span><small>{records.length}</small></div><div className="ecRecords">{records.slice(0,30).map(r=><div key={r.id}><span><strong>{r.field_code}</strong><small>{r.occurred_on} · {r.source}</small></span><b>{num(r.tons,1)} t</b><em>{r.atr_kg_t==null?'ATR —':`ATR ${num(r.atr_kg_t,1)}`}</em><strong>{money(r.revenue_amount??r.calculated_revenue)}</strong></div>)}{!records.length&&<small>Nenhum lançamento de produção.</small>}</div></section></div>}

function FinanceSection({fields,seasonId,role,records,summary,onSaved}:{fields:Field[];seasonId:string;role:string;records:Cost[];summary:EconSummary|null;onSaved:()=>Promise<void>}){const can=financeRoles.has(role);const [fieldId,setFieldId]=useState('');const [date,setDate]=useState(localDate());const [category,setCategory]=useState('');const [amount,setAmount]=useState('');const [supplier,setSupplier]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/v1/costs',{method:'POST',body:JSON.stringify({fieldId:fieldId||undefined,seasonId,occurredOn:date,category,amount:Number(amount),supplier:supplier||undefined})});setCategory('');setAmount('');setSupplier('');await onSaved();}catch(e){setError(e instanceof Error?e.message:'Falha ao lançar custo.');}finally{setBusy(false);}}return <><section className="ecSubKpis"><Card label="CUSTO TOTAL" value={money(summary?.total_cost)}/><Card label="NÃO ALOCADO" value={money(summary?.unallocated_cost)}/><Card label="MARGEM TOTAL" value={money(summary?.margin)} warn={Number(summary?.margin??0)<0}/></section><div className="ecGrid">{can&&<form className="panel ecForm" onSubmit={submit}><div className="panelTitle"><span>LANÇAR CUSTO</span><small>manual</small></div><label>Alocação<select value={fieldId} onChange={e=>setFieldId(e.target.value)}><option value="">Geral da safra</option>{fields.map(f=><option key={f.id} value={f.id}>{f.code}</option>)}</select></label><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Categoria<input value={category} onChange={e=>setCategory(e.target.value)} required placeholder="Ex.: Fertilizantes"/></label><label>Valor<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Fornecedor<input value={supplier} onChange={e=>setSupplier(e.target.value)} /></label>{error&&<div className="formError">{error}</div>}<button className="primaryButton" disabled={busy}>{busy?'Salvando…':'Salvar custo'}</button></form>}<section className="panel"><div className="panelTitle"><span>ÚLTIMOS CUSTOS</span><small>{records.length}</small></div><div className="ecRecords">{records.slice(0,40).map(r=><div key={r.id}><span><strong>{r.category}</strong><small>{r.occurred_on} · {r.field_code??'geral da safra'}</small></span><b>{money(r.amount)}</b><em>{r.supplier??'—'}</em></div>)}{!records.length&&<small>Nenhum custo registrado.</small>}</div></section></div></>}
function Card({label,value,warn=false}:{label:string;value:string;warn?:boolean}){return <div className="kpi"><small>{label}</small><strong className={warn?'warning':''}>{value}</strong></div>}
