import { useEffect, useMemo, useState } from 'react';
import { getApiToken } from './auth';

type FieldLite={id:string;code:string;area_ha:string|number|null;variety?:string|null};
type Props={farmId:string;seasonId:string;fields:FieldLite[];role:string;section:'Colheita'|'CTT'|'Usinas'};
type Mill={id:string;name:string;municipality:string|null;state:string|null;distance_km:string|number|null;default_atr_price_per_kg:string|number|null};
type Plan={id:string;field_id:string;mill_id:string|null;field_code:string;area_ha:string|number|null;variety:string|null;mill_name:string|null;planned_start:string|null;planned_end:string|null;priority:'low'|'normal'|'high'|'critical';expected_tons:string|number|null;delivered_tons:string|number;status:'planned'|'ready'|'harvesting'|'completed'|'cancelled'};
type LoadStatus='cutting'|'loaded'|'in_transit'|'arrived'|'delivered'|'rejected'|'cancelled';
type Load={id:string;harvest_plan_id:string|null;field_id:string;mill_id:string|null;field_code:string;mill_name:string|null;ticket_number:string|null;vehicle_plate:string|null;driver_name:string|null;status:LoadStatus;cut_at:string|null;loaded_at:string|null;departed_at:string|null;arrived_mill_at:string|null;weighed_at:string|null;milled_at:string|null;net_tons:string|number|null;atr_kg_t:string|number|null;atr_price_per_kg:string|number|null;revenue_amount:string|number|null;impurities_pct:string|number|null;fiber_pct:string|number|null;cut_to_load_minutes:string|number|null;load_to_mill_minutes:string|number|null;ctt_total_minutes:string|number|null};
type Summary={active_loads:string|number;delivered_loads:string|number;delivered_tons:string|number;atr_kg_t:string|number|null;avg_ctt_minutes:string|number|null;ctt_alerts:string|number;revenue:string|number;queued_plans:string|number;harvesting_plans:string|number;queued_tons:string|number};
type MillPerformance=Mill&{loads:string|number;tons:string|number;atr_kg_t:string|number|null;avg_ctt_minutes:string|number|null;revenue:string|number};
type ApiEnvelope<T>={data:T};
const apiBase=(import.meta.env.VITE_API_URL as string|undefined)??'';
const managementRoles=new Set(['owner','admin','manager','agronomist']);
const money=(v:unknown)=>Number(v??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const num=(v:unknown,d=1)=>Number(v??0).toLocaleString('pt-BR',{maximumFractionDigits:d});
const date=(v:string|null)=>v?new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const dateTime=(v:string|null)=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
const statusLabel:Record<LoadStatus,string>={cutting:'Cortando',loaded:'Carregada',in_transit:'Em trânsito',arrived:'Na usina',delivered:'Entregue',rejected:'Rejeitada',cancelled:'Cancelada'};

async function api<T>(path:string,init?:RequestInit):Promise<T>{const token=await getApiToken();if(!token)throw new Error('Sessão expirada.');const response=await fetch(`${apiBase}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers??{})}});const body=await response.json().catch(()=>({})) as {error?:string};if(!response.ok)throw new Error(body.error??'api_error');return body as T;}

export function HarvestPanel({farmId,seasonId,fields,role,section}:Props){
  const [mills,setMills]=useState<Mill[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[loads,setLoads]=useState<Load[]>([]);const[summary,setSummary]=useState<Summary|null>(null);const[performance,setPerformance]=useState<MillPerformance[]>([]);
  const[showPlan,setShowPlan]=useState(false);const[showLoad,setShowLoad]=useState(false);const[showMill,setShowMill]=useState(false);const[delivery,setDelivery]=useState<{load:Load;tons:string;atr:string;price:string;revenue:string;impurities:string;fiber:string}|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const canManage=managementRoles.has(role);

  async function load(){if(!farmId||!seasonId)return;setBusy(true);setError('');try{const suffix=`seasonId=${encodeURIComponent(seasonId)}&farmId=${encodeURIComponent(farmId)}`;const[millResult,planResult,loadResult,summaryResult,performanceResult]=await Promise.all([api<ApiEnvelope<Mill[]>>('/api/v1/mills'),api<ApiEnvelope<Plan[]>>(`/api/v1/harvest/plans?${suffix}`),api<ApiEnvelope<Load[]>>(`/api/v1/harvest/loads?${suffix}`),api<ApiEnvelope<Summary>>(`/api/v1/harvest/summary?${suffix}`),api<ApiEnvelope<MillPerformance[]>>(`/api/v1/harvest/mills-performance?seasonId=${encodeURIComponent(seasonId)}`)]);setMills(millResult.data);setPlans(planResult.data);setLoads(loadResult.data);setSummary(summaryResult.data);setPerformance(performanceResult.data);}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao carregar colheita.');}finally{setBusy(false)}}
  useEffect(()=>{void load()},[farmId,seasonId]);
  const activeLoads=useMemo(()=>loads.filter(l=>!['delivered','rejected','cancelled'].includes(l.status)),[loads]);

  async function loadAction(item:Load,action:'loaded'|'depart'|'arrive'){setBusy(true);setError('');try{await api(`/api/v1/harvest/loads/${item.id}/${action}`,{method:'POST',body:'{}'});await load()}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao atualizar carga.')}finally{setBusy(false)}}
  async function deliver(){if(!delivery)return;setBusy(true);setError('');try{await api(`/api/v1/harvest/loads/${delivery.load.id}/deliver`,{method:'POST',body:JSON.stringify({netTons:Number(delivery.tons),atrKgT:delivery.atr?Number(delivery.atr):undefined,atrPricePerKg:delivery.price?Number(delivery.price):undefined,revenueAmount:delivery.revenue?Number(delivery.revenue):undefined,impuritiesPct:delivery.impurities?Number(delivery.impurities):undefined,fiberPct:delivery.fiber?Number(delivery.fiber):undefined})});setDelivery(null);await load()}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao entregar carga.')}finally{setBusy(false)}}

  return <div className="harvestPage">
    <section className="harvestKpis"><HarvestKpi label="FILA COLHEITA" value={`${Number(summary?.queued_plans??0)}`} note={`${num(summary?.queued_tons,0)} t previstas`}/><HarvestKpi label="CARGAS ATIVAS" value={`${Number(summary?.active_loads??0)}`} note={`${Number(summary?.harvesting_plans??0)} talhões em colheita`}/><HarvestKpi label="ENTREGUE" value={`${num(summary?.delivered_tons,0)} t`} note={`ATR ${summary?.atr_kg_t==null?'—':num(summary.atr_kg_t,1)} kg/t`}/><HarvestKpi label="CTT MÉDIO" value={summary?.avg_ctt_minutes==null?'—':`${num(summary.avg_ctt_minutes,0)} min`} note={`${Number(summary?.ctt_alerts??0)} alertas > 180 min`} warn={Number(summary?.ctt_alerts??0)>0}/></section>
    <div className="harvestNav"><button className={section==='Colheita'?'active':''}>Colheita</button><button className={section==='CTT'?'active':''}>CTT</button><button className={section==='Usinas'?'active':''}>Usinas</button><span>{busy?'Atualizando…':'Dados da safra selecionada'}</span></div>
    {error&&<div className="harvestError">{error}</div>}

    {section==='Colheita'&&<>
      <section className="panel harvestTools"><div><strong>Gestão da colheita</strong><span>Fila, corte, carregamento e entrega</span></div><div><button onClick={()=>void load()} disabled={busy}>Atualizar</button>{canManage&&<button onClick={()=>setShowPlan(v=>!v)}>+ Planejar talhão</button>}<button className="harvestPrimary" onClick={()=>setShowLoad(v=>!v)}>+ Nova carga</button></div></section>
      {showPlan&&<PlanForm farmId={farmId} seasonId={seasonId} fields={fields} mills={mills} onSaved={async()=>{setShowPlan(false);await load()}}/>}
      {showLoad&&<LoadForm farmId={farmId} seasonId={seasonId} fields={fields} mills={mills} plans={plans} onSaved={async()=>{setShowLoad(false);await load()}}/>}
      <section className="panel"><div className="panelTitle"><span>FILA DE TALHÕES</span><small>prioridade de colheita</small></div><div className="harvestPlanGrid">{plans.map(plan=><article key={plan.id}><div><strong>{plan.field_code}</strong><span className={`harvestPriority ${plan.priority}`}>{plan.priority}</span></div><p>{plan.variety??'Variedade —'} · {num(plan.area_ha)} ha · {plan.mill_name??'Usina não definida'}</p><div className="harvestProgress"><i style={{width:`${Math.min(100,Number(plan.expected_tons??0)>0?Number(plan.delivered_tons??0)/Number(plan.expected_tons)*100:0)}%`}}/></div><small>{num(plan.delivered_tons,0)} / {num(plan.expected_tons,0)} t · início {date(plan.planned_start)} · {plan.status}</small></article>)}{!plans.length&&<div className="emptyState">Nenhum talhão planejado para colheita.</div>}</div></section>
      <section className="panel"><div className="panelTitle"><span>CARGAS EM MOVIMENTO</span><small>{activeLoads.length} ativas</small></div><div className="harvestLoads">{activeLoads.map(item=><article key={item.id}><div className="loadTop"><strong>{item.field_code}</strong><span className={`loadStatus ${item.status}`}>{statusLabel[item.status]}</span><small>{item.vehicle_plate??'sem placa'} · {item.mill_name??'sem usina'}</small></div><div className="loadTimes"><span>Corte <b>{dateTime(item.cut_at)}</b></span><span>Carregado <b>{dateTime(item.loaded_at)}</b></span><span>Usina <b>{dateTime(item.arrived_mill_at)}</b></span></div><div className="loadActions">{item.status==='cutting'&&<button onClick={()=>void loadAction(item,'loaded')}>Carga concluída</button>}{item.status==='loaded'&&<button onClick={()=>void loadAction(item,'depart')}>Sair para usina</button>}{item.status==='in_transit'&&<button onClick={()=>void loadAction(item,'arrive')}>Chegou à usina</button>}{['loaded','in_transit','arrived'].includes(item.status)&&<button className="harvestPrimary" onClick={()=>setDelivery({load:item,tons:'',atr:'',price:String(mills.find(m=>m.id===item.mill_id)?.default_atr_price_per_kg??''),revenue:'',impurities:'',fiber:''})}>Pesar / entregar</button>}</div></article>)}{!activeLoads.length&&<div className="emptyState">Nenhuma carga ativa.</div>}</div></section>
    </>}

    {section==='CTT'&&<section className="panel"><div className="panelTitle"><span>CONTROLE CTT — CORTE AO PROCESSAMENTO</span><small>alerta operacional: 180 min</small></div><div className="cttTableWrap"><table className="cttTable"><thead><tr><th>Talhão</th><th>Carga</th><th>Status</th><th>Corte→Carga</th><th>Carga→Usina</th><th>Total CTT</th><th>t</th><th>ATR</th></tr></thead><tbody>{loads.map(item=><tr key={item.id} className={Number(item.ctt_total_minutes??0)>180?'cttAlert':''}><td><strong>{item.field_code}</strong></td><td>{item.ticket_number??item.vehicle_plate??'—'}</td><td>{statusLabel[item.status]}</td><td>{item.cut_to_load_minutes==null?'—':`${num(item.cut_to_load_minutes,0)} min`}</td><td>{item.load_to_mill_minutes==null?'—':`${num(item.load_to_mill_minutes,0)} min`}</td><td>{item.ctt_total_minutes==null?'em aberto':`${num(item.ctt_total_minutes,0)} min`}</td><td>{item.net_tons==null?'—':num(item.net_tons,1)}</td><td>{item.atr_kg_t==null?'—':num(item.atr_kg_t,1)}</td></tr>)}{!loads.length&&<tr><td colSpan={8} className="emptyState">Sem cargas para medir CTT.</td></tr>}</tbody></table></div></section>}

    {section==='Usinas'&&<><section className="panel harvestTools"><div><strong>Usinas parceiras / destinos</strong><span>ATR, distância, CTT e receita</span></div><div>{canManage&&<button className="harvestPrimary" onClick={()=>setShowMill(v=>!v)}>+ Cadastrar usina</button>}</div></section>{showMill&&<MillForm onSaved={async()=>{setShowMill(false);await load()}}/>}<section className="millGrid">{performance.map(mill=><article key={mill.id}><div className="millHead"><strong>{mill.name}</strong><span>{mill.municipality??'—'}/{mill.state??'—'}</span></div><div className="millStats"><div><small>TONELADAS</small><strong>{num(mill.tons,0)} t</strong></div><div><small>ATR</small><strong>{mill.atr_kg_t==null?'—':num(mill.atr_kg_t,1)}</strong></div><div><small>CTT MÉDIO</small><strong>{mill.avg_ctt_minutes==null?'—':`${num(mill.avg_ctt_minutes,0)} min`}</strong></div><div><small>RECEITA</small><strong>{money(mill.revenue)}</strong></div></div><footer>{mill.distance_km==null?'Distância não cadastrada':`${num(mill.distance_km,1)} km`} · {Number(mill.loads??0)} cargas</footer></article>)}{!performance.length&&<div className="emptyState panel">Cadastre a primeira usina para iniciar a comparação.</div>}</section></>}

    {delivery&&<div className="harvestModalBackdrop"><div className="harvestModal"><h3>Pesagem / entrega — {delivery.load.field_code}</h3><p>Ao confirmar, toneladas e ATR serão lançados automaticamente em Produção.</p><div className="harvestFormGrid"><label>Toneladas líquidas<input type="number" min="0.001" step="0.001" required value={delivery.tons} onChange={e=>setDelivery({...delivery,tons:e.target.value})}/></label><label>ATR kg/t<input type="number" min="0" step="0.01" value={delivery.atr} onChange={e=>setDelivery({...delivery,atr:e.target.value})}/></label><label>R$/kg ATR<input type="number" min="0" step="0.000001" value={delivery.price} onChange={e=>setDelivery({...delivery,price:e.target.value})}/></label><label>Receita real R$<input type="number" min="0" step="0.01" value={delivery.revenue} onChange={e=>setDelivery({...delivery,revenue:e.target.value})}/></label><label>Impureza %<input type="number" min="0" max="100" step="0.01" value={delivery.impurities} onChange={e=>setDelivery({...delivery,impurities:e.target.value})}/></label><label>Fibra %<input type="number" min="0" max="100" step="0.01" value={delivery.fiber} onChange={e=>setDelivery({...delivery,fiber:e.target.value})}/></label></div><div className="harvestModalActions"><button onClick={()=>setDelivery(null)}>Voltar</button><button className="harvestPrimary" onClick={()=>void deliver()} disabled={busy||!delivery.tons}>Confirmar entrega</button></div></div></div>}
  </div>;
}

function PlanForm({farmId,seasonId,fields,mills,onSaved}:{farmId:string;seasonId:string;fields:FieldLite[];mills:Mill[];onSaved:()=>Promise<void>}){const[fieldId,setFieldId]=useState(fields[0]?.id??'');const[millId,setMillId]=useState('');const[start,setStart]=useState('');const[tons,setTons]=useState('');const[priority,setPriority]=useState<'low'|'normal'|'high'|'critical'>('normal');const[busy,setBusy]=useState(false);const[error,setError]=useState('');useEffect(()=>{if(!fieldId&&fields[0])setFieldId(fields[0].id)},[fields,fieldId]);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/v1/harvest/plans',{method:'POST',body:JSON.stringify({farmId,fieldId,seasonId,millId:millId||undefined,plannedStart:start||undefined,priority,expectedTons:tons?Number(tons):undefined})});await onSaved()}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao planejar colheita.')}finally{setBusy(false)}}return <form className="panel harvestForm" onSubmit={submit}><h3>Planejar colheita</h3><div className="harvestFormGrid"><label>Talhão<select value={fieldId} onChange={e=>setFieldId(e.target.value)}>{fields.map(f=><option key={f.id} value={f.id}>{f.code} · {num(f.area_ha)} ha</option>)}</select></label><label>Usina<select value={millId} onChange={e=>setMillId(e.target.value)}><option value="">Definir depois</option>{mills.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Início previsto<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Toneladas previstas<input type="number" min="0" step="0.1" value={tons} onChange={e=>setTons(e.target.value)}/></label><label>Prioridade<select value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label></div>{error&&<div className="harvestError">{error}</div>}<button className="harvestPrimary" disabled={busy||!fieldId}>{busy?'Salvando…':'Adicionar à fila'}</button></form>}

function LoadForm({farmId,seasonId,fields,mills,plans,onSaved}:{farmId:string;seasonId:string;fields:FieldLite[];mills:Mill[];plans:Plan[];onSaved:()=>Promise<void>}){const[fieldId,setFieldId]=useState(fields[0]?.id??'');const[planId,setPlanId]=useState('');const[millId,setMillId]=useState('');const[plate,setPlate]=useState('');const[driver,setDriver]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');useEffect(()=>{if(!fieldId&&fields[0])setFieldId(fields[0].id)},[fields,fieldId]);function choosePlan(id:string){setPlanId(id);const p=plans.find(x=>x.id===id);if(p){setFieldId(p.field_id);setMillId(p.mill_id??'')}}async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/v1/harvest/loads',{method:'POST',body:JSON.stringify({farmId,fieldId,seasonId,harvestPlanId:planId||undefined,millId:millId||undefined,vehiclePlate:plate||undefined,driverName:driver||undefined,cutAt:new Date().toISOString()})});await onSaved()}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao abrir carga.')}finally{setBusy(false)}}return <form className="panel harvestForm" onSubmit={submit}><h3>Abrir nova carga</h3><div className="harvestFormGrid"><label>Plano<select value={planId} onChange={e=>choosePlan(e.target.value)}><option value="">Sem plano vinculado</option>{plans.filter(p=>!['completed','cancelled'].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.field_code} · {p.status}</option>)}</select></label><label>Talhão<select value={fieldId} onChange={e=>setFieldId(e.target.value)} required>{fields.map(f=><option key={f.id} value={f.id}>{f.code}</option>)}</select></label><label>Usina<select value={millId} onChange={e=>setMillId(e.target.value)}><option value="">Sem destino</option>{mills.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Placa<input value={plate} onChange={e=>setPlate(e.target.value.toUpperCase())} placeholder="ABC1D23"/></label><label>Motorista<input value={driver} onChange={e=>setDriver(e.target.value)}/></label></div>{error&&<div className="harvestError">{error}</div>}<button className="harvestPrimary" disabled={busy||!fieldId}>{busy?'Abrindo…':'Iniciar corte / carga'}</button></form>}

function MillForm({onSaved}:{onSaved:()=>Promise<void>}){const[name,setName]=useState('');const[city,setCity]=useState('');const[state,setState]=useState('SP');const[distance,setDistance]=useState('');const[price,setPrice]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/v1/mills',{method:'POST',body:JSON.stringify({name,municipality:city||undefined,state,distanceKm:distance?Number(distance):undefined,defaultAtrPricePerKg:price?Number(price):undefined})});await onSaved()}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao cadastrar usina.')}finally{setBusy(false)}}return <form className="panel harvestForm" onSubmit={submit}><h3>Nova usina</h3><div className="harvestFormGrid"><label>Nome<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Município<input value={city} onChange={e=>setCity(e.target.value)}/></label><label>UF<input maxLength={2} value={state} onChange={e=>setState(e.target.value.toUpperCase().slice(0,2))}/></label><label>Distância km<input type="number" min="0" step="0.1" value={distance} onChange={e=>setDistance(e.target.value)}/></label><label>R$/kg ATR padrão<input type="number" min="0" step="0.000001" value={price} onChange={e=>setPrice(e.target.value)}/></label></div>{error&&<div className="harvestError">{error}</div>}<button className="harvestPrimary" disabled={busy}>{busy?'Salvando…':'Cadastrar usina'}</button></form>}
function HarvestKpi({label,value,note,warn=false}:{label:string;value:string;note:string;warn?:boolean}){return <div className="harvestKpi"><small>{label}</small><strong className={warn?'warning':''}>{value}</strong><span>{note}</span></div>}
