import { Hono } from 'hono';
import { neon } from '@neondatabase/serverless';
import { z } from 'zod';

type Role='owner'|'admin'|'manager'|'agronomist'|'operator'|'viewer';
type AgronomyEnv={Bindings:{DATABASE_URL:string};Variables:{authUserId:string;organizationId:string;role:Role}};
type Db=any;
const manageRoles=new Set<Role>(['owner','admin','manager','agronomist']);
const executeRoles=new Set<Role>(['owner','admin','manager','agronomist','operator']);
const uuid=z.uuid();

const point=z.object({latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180)}).optional();
const soilInput=z.object({
  farmId:z.uuid(),fieldId:z.uuid(),seasonId:z.uuid().optional(),sampleCode:z.string().trim().min(1).max(100),sampledOn:z.iso.date(),
  depthFromCm:z.number().nonnegative().max(500).default(0),depthToCm:z.number().positive().max(500).default(20),location:point,laboratory:z.string().trim().max(180).optional(),
  ph:z.number().min(0).max(14).optional(),organicMatterGdm3:z.number().nonnegative().optional(),phosphorusMgdm3:z.number().nonnegative().optional(),potassiumMmolcDm3:z.number().nonnegative().optional(),
  calciumMmolcDm3:z.number().nonnegative().optional(),magnesiumMmolcDm3:z.number().nonnegative().optional(),sulfurMgdm3:z.number().nonnegative().optional(),boronMgdm3:z.number().nonnegative().optional(),
  zincMgdm3:z.number().nonnegative().optional(),manganeseMgdm3:z.number().nonnegative().optional(),copperMgdm3:z.number().nonnegative().optional(),ironMgdm3:z.number().nonnegative().optional(),
  cecMmolcDm3:z.number().nonnegative().optional(),baseSaturationPct:z.number().min(0).max(100).optional(),clayPct:z.number().min(0).max(100).optional(),sandPct:z.number().min(0).max(100).optional(),siltPct:z.number().min(0).max(100).optional(),notes:z.string().trim().max(3000).optional(),
}).refine(v=>v.depthToCm>v.depthFromCm,{message:'depth_to_must_be_greater'});
const pestInput=z.object({
  farmId:z.uuid(),fieldId:z.uuid(),seasonId:z.uuid().optional(),category:z.enum(['pest','disease','weed','other']),name:z.string().trim().min(2).max(180),observedOn:z.iso.date(),severity:z.number().int().min(1).max(5),
  infestationPct:z.number().min(0).max(100).optional(),infestedAreaHa:z.number().nonnegative().optional(),location:point,notes:z.string().trim().max(3000).optional(),
});
const pestPatch=z.object({status:z.enum(['open','monitoring','treated','closed']).optional(),severity:z.number().int().min(1).max(5).optional(),infestationPct:z.number().min(0).max(100).nullable().optional(),infestedAreaHa:z.number().nonnegative().nullable().optional(),notes:z.string().trim().max(3000).nullable().optional()});
const actionInput=z.object({workOrderId:z.uuid().optional(),actionType:z.string().trim().min(2).max(120),occurredOn:z.iso.date(),productName:z.string().trim().max(180).optional(),dose:z.number().nonnegative().optional(),doseUnit:z.string().trim().max(40).optional(),result:z.string().trim().max(1000).optional(),notes:z.string().trim().max(3000).optional(),markTreated:z.boolean().default(true)});

function qUuid(v:string|undefined){if(!v)return{value:undefined as string|undefined,invalid:false};const p=uuid.safeParse(v);return p.success?{value:p.data,invalid:false}:{value:undefined,invalid:true};}
async function validateScope(db:Db,orgId:string,farmId:string,fieldId:string,seasonId?:string){const f=await db`SELECT id,farm_id FROM fields WHERE id=${fieldId} AND organization_id=${orgId} AND active=true LIMIT 1`;if(!f[0])return'field_not_found';if(f[0].farm_id!==farmId)return'field_farm_mismatch';const farm=await db`SELECT id FROM farms WHERE id=${farmId} AND organization_id=${orgId} LIMIT 1`;if(!farm[0])return'farm_not_found';if(seasonId){const s=await db`SELECT id FROM seasons WHERE id=${seasonId} AND organization_id=${orgId} LIMIT 1`;if(!s[0])return'season_not_found';}return null;}

export function registerAgronomyRoutes(app:Hono<AgronomyEnv>){
  app.get('/api/v1/soil/samples',async c=>{const farm=qUuid(c.req.query('farmId')),field=qUuid(c.req.query('fieldId')),season=qUuid(c.req.query('seasonId'));if(farm.invalid||field.invalid||season.invalid)return c.json({error:'invalid_filter'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT ss.id,ss.farm_id,ss.field_id,ss.season_id,ss.sample_code,ss.sampled_on,ss.depth_from_cm,ss.depth_to_cm,CASE WHEN ss.location IS NOT NULL THEN ST_AsGeoJSON(ss.location)::json ELSE NULL END AS location,ss.laboratory,ss.ph,ss.organic_matter_g_dm3,ss.phosphorus_mg_dm3,ss.potassium_mmolc_dm3,ss.calcium_mmolc_dm3,ss.magnesium_mmolc_dm3,ss.sulfur_mg_dm3,ss.boron_mg_dm3,ss.zinc_mg_dm3,ss.manganese_mg_dm3,ss.copper_mg_dm3,ss.iron_mg_dm3,ss.cec_mmolc_dm3,ss.base_saturation_pct,ss.clay_pct,ss.sand_pct,ss.silt_pct,ss.notes,ss.created_at,f.code AS field_code,f.variety FROM soil_samples ss JOIN fields f ON f.id=ss.field_id WHERE ss.organization_id=${orgId} AND (${farm.value??null}::uuid IS NULL OR ss.farm_id=${farm.value??null}::uuid) AND (${field.value??null}::uuid IS NULL OR ss.field_id=${field.value??null}::uuid) AND (${season.value??null}::uuid IS NULL OR ss.season_id=${season.value??null}::uuid) ORDER BY ss.sampled_on DESC,ss.created_at DESC LIMIT 1000`;return c.json({data:rows});});

  app.post('/api/v1/soil/samples',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=soilInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const scope=await validateScope(db,orgId,b.farmId,b.fieldId,b.seasonId);if(scope)return c.json({error:scope},404);const rows=await db`INSERT INTO soil_samples(organization_id,farm_id,field_id,season_id,sample_code,sampled_on,depth_from_cm,depth_to_cm,location,laboratory,ph,organic_matter_g_dm3,phosphorus_mg_dm3,potassium_mmolc_dm3,calcium_mmolc_dm3,magnesium_mmolc_dm3,sulfur_mg_dm3,boron_mg_dm3,zinc_mg_dm3,manganese_mg_dm3,copper_mg_dm3,iron_mg_dm3,cec_mmolc_dm3,base_saturation_pct,clay_pct,sand_pct,silt_pct,notes) VALUES(${orgId},${b.farmId},${b.fieldId},${b.seasonId??null},${b.sampleCode},${b.sampledOn},${b.depthFromCm},${b.depthToCm},CASE WHEN ${b.location?true:false} THEN ST_SetSRID(ST_MakePoint(${b.location?.longitude??0},${b.location?.latitude??0}),4326) ELSE NULL END,${b.laboratory??null},${b.ph??null},${b.organicMatterGdm3??null},${b.phosphorusMgdm3??null},${b.potassiumMmolcDm3??null},${b.calciumMmolcDm3??null},${b.magnesiumMmolcDm3??null},${b.sulfurMgdm3??null},${b.boronMgdm3??null},${b.zincMgdm3??null},${b.manganeseMgdm3??null},${b.copperMgdm3??null},${b.ironMgdm3??null},${b.cecMmolcDm3??null},${b.baseSaturationPct??null},${b.clayPct??null},${b.sandPct??null},${b.siltPct??null},${b.notes??null}) RETURNING *`;return c.json({data:rows[0]},201);});

  app.get('/api/v1/soil/summary',async c=>{const farm=qUuid(c.req.query('farmId')),season=qUuid(c.req.query('seasonId'));if(farm.invalid||season.invalid)return c.json({error:'invalid_filter'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const [row]=await db`SELECT COUNT(*) AS samples,COUNT(DISTINCT field_id) AS sampled_fields,ROUND(AVG(ph),2) AS avg_ph,ROUND(AVG(organic_matter_g_dm3),2) AS avg_organic_matter,ROUND(AVG(phosphorus_mg_dm3),2) AS avg_phosphorus,ROUND(AVG(potassium_mmolc_dm3),2) AS avg_potassium,ROUND(AVG(base_saturation_pct),2) AS avg_base_saturation,MAX(sampled_on) AS latest_sample FROM soil_samples WHERE organization_id=${orgId} AND (${farm.value??null}::uuid IS NULL OR farm_id=${farm.value??null}::uuid) AND (${season.value??null}::uuid IS NULL OR season_id=${season.value??null}::uuid)`;return c.json({data:row??{}});});

  app.get('/api/v1/pests/summary',async c=>{const farm=qUuid(c.req.query('farmId')),season=qUuid(c.req.query('seasonId'));if(farm.invalid||season.invalid)return c.json({error:'invalid_filter'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const [row]=await db`SELECT COUNT(*) FILTER(WHERE status IN('open','monitoring')) AS active,COUNT(*) FILTER(WHERE status IN('open','monitoring') AND severity>=4) AS high_severity,COUNT(*) FILTER(WHERE status='treated') AS treated,COUNT(*) FILTER(WHERE status='closed') AS closed,ROUND(AVG(severity) FILTER(WHERE status IN('open','monitoring')),2) AS avg_active_severity,COALESCE(SUM(infested_area_ha) FILTER(WHERE status IN('open','monitoring')),0) AS active_area_ha FROM pest_occurrences WHERE organization_id=${orgId} AND (${farm.value??null}::uuid IS NULL OR farm_id=${farm.value??null}::uuid) AND (${season.value??null}::uuid IS NULL OR season_id=${season.value??null}::uuid)`;return c.json({data:row??{}});});

  app.get('/api/v1/pests',async c=>{const farm=qUuid(c.req.query('farmId')),field=qUuid(c.req.query('fieldId')),season=qUuid(c.req.query('seasonId'));if(farm.invalid||field.invalid||season.invalid)return c.json({error:'invalid_filter'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT po.id,po.farm_id,po.field_id,po.season_id,po.category,po.name,po.observed_on,po.severity,po.infestation_pct,po.infested_area_ha,po.status,CASE WHEN po.location IS NOT NULL THEN ST_AsGeoJSON(po.location)::json ELSE NULL END AS location,CASE WHEN po.affected_geometry IS NOT NULL THEN ST_AsGeoJSON(po.affected_geometry)::json ELSE NULL END AS affected_geometry,po.notes,po.created_by,po.created_at,po.updated_at,f.code AS field_code,(SELECT COUNT(*) FROM pest_actions pa WHERE pa.pest_occurrence_id=po.id) AS action_count FROM pest_occurrences po JOIN fields f ON f.id=po.field_id WHERE po.organization_id=${orgId} AND (${farm.value??null}::uuid IS NULL OR po.farm_id=${farm.value??null}::uuid) AND (${field.value??null}::uuid IS NULL OR po.field_id=${field.value??null}::uuid) AND (${season.value??null}::uuid IS NULL OR po.season_id=${season.value??null}::uuid) ORDER BY CASE po.status WHEN 'open' THEN 1 WHEN 'monitoring' THEN 2 WHEN 'treated' THEN 3 ELSE 4 END,po.severity DESC,po.observed_on DESC`;return c.json({data:rows});});

  app.post('/api/v1/pests',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=pestInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const scope=await validateScope(db,orgId,b.farmId,b.fieldId,b.seasonId);if(scope)return c.json({error:scope},404);const rows=await db`INSERT INTO pest_occurrences(organization_id,farm_id,field_id,season_id,category,name,observed_on,severity,infestation_pct,infested_area_ha,location,notes,created_by) VALUES(${orgId},${b.farmId},${b.fieldId},${b.seasonId??null},${b.category},${b.name},${b.observedOn},${b.severity},${b.infestationPct??null},${b.infestedAreaHa??null},CASE WHEN ${b.location?true:false} THEN ST_SetSRID(ST_MakePoint(${b.location?.longitude??0},${b.location?.latitude??0}),4326) ELSE NULL END,${b.notes??null},${c.get('authUserId')}) RETURNING *`;return c.json({data:rows[0]},201);});

  app.patch('/api/v1/pests/:id',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id')),p=pestPatch.safeParse(await c.req.json());if(!id.success)return c.json({error:'invalid_occurrence'},400);if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const b=p.data,db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`UPDATE pest_occurrences SET status=COALESCE(${b.status??null},status),severity=COALESCE(${b.severity??null},severity),infestation_pct=CASE WHEN ${b.infestationPct!==undefined}::boolean THEN ${b.infestationPct??null}::numeric ELSE infestation_pct END,infested_area_ha=CASE WHEN ${b.infestedAreaHa!==undefined}::boolean THEN ${b.infestedAreaHa??null}::numeric ELSE infested_area_ha END,notes=CASE WHEN ${b.notes!==undefined}::boolean THEN ${b.notes??null} ELSE notes END,updated_at=now() WHERE id=${id.data} AND organization_id=${orgId} RETURNING *`;if(!rows[0])return c.json({error:'occurrence_not_found'},404);return c.json({data:rows[0]});});

  app.get('/api/v1/pests/:id/actions',async c=>{const id=uuid.safeParse(c.req.param('id'));if(!id.success)return c.json({error:'invalid_occurrence'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT pa.*,wo.number AS work_order_number FROM pest_actions pa LEFT JOIN work_orders wo ON wo.id=pa.work_order_id WHERE pa.organization_id=${orgId} AND pa.pest_occurrence_id=${id.data} ORDER BY pa.occurred_on DESC,pa.created_at DESC`;return c.json({data:rows});});

  app.post('/api/v1/pests/:id/actions',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id')),p=actionInput.safeParse(await c.req.json());if(!id.success)return c.json({error:'invalid_occurrence'},400);if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const occ=await db`SELECT id FROM pest_occurrences WHERE id=${id.data} AND organization_id=${orgId} LIMIT 1`;if(!occ[0])return c.json({error:'occurrence_not_found'},404);if(b.workOrderId){const wo=await db`SELECT id FROM work_orders WHERE id=${b.workOrderId} AND organization_id=${orgId} LIMIT 1`;if(!wo[0])return c.json({error:'work_order_not_found'},404);}const rows=await db`INSERT INTO pest_actions(organization_id,pest_occurrence_id,work_order_id,action_type,occurred_on,product_name,dose,dose_unit,result,notes) VALUES(${orgId},${id.data},${b.workOrderId??null},${b.actionType},${b.occurredOn},${b.productName??null},${b.dose??null},${b.doseUnit??null},${b.result??null},${b.notes??null}) RETURNING *`;if(b.markTreated)await db`UPDATE pest_occurrences SET status='treated',updated_at=now() WHERE id=${id.data} AND organization_id=${orgId} AND status<>'closed'`;return c.json({data:rows[0]},201);});

  app.post('/api/v1/pests/:id/work-order',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id'));if(!id.success)return c.json({error:'invalid_occurrence'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT id,farm_id,field_id,season_id,name,severity,status FROM pest_occurrences WHERE id=${id.data} AND organization_id=${orgId} LIMIT 1`;const o=rows[0] as any;if(!o)return c.json({error:'occurrence_not_found'},404);const priority=o.severity>=5?'critical':o.severity>=4?'high':'normal';const woRows=await db`INSERT INTO work_orders(organization_id,farm_id,field_id,season_id,operation_type,title,status,priority,notes) VALUES(${orgId},${o.farm_id},${o.field_id},${o.season_id},'pest_control',${`Controle: ${o.name}`},'planned',${priority},${`Gerada pela ocorrência ${o.id}`}) RETURNING *`;const wo=woRows[0] as any;await db`INSERT INTO work_order_events(organization_id,work_order_id,event_type,to_status,actor_id,notes,metadata) VALUES(${orgId},${wo.id},'created','planned',${c.get('authUserId')},${`OS criada a partir de ocorrência agronômica ${o.name}`},${JSON.stringify({pestOccurrenceId:o.id,severity:o.severity})}::jsonb)`;await db`UPDATE pest_occurrences SET status=CASE WHEN status='open' THEN 'monitoring' ELSE status END,updated_at=now() WHERE id=${o.id}`;return c.json({data:wo},201);});
}
