import { Hono } from 'hono';
import { neon } from '@neondatabase/serverless';
import { z } from 'zod';

type Role = 'owner'|'admin'|'manager'|'agronomist'|'operator'|'viewer';
type AssetsEnv = { Bindings:{DATABASE_URL:string}; Variables:{authUserId:string;organizationId:string;role:Role} };
type Db = any;
const manageRoles = new Set<Role>(['owner','admin','manager']);
const executeRoles = new Set<Role>(['owner','admin','manager','agronomist','operator']);
const uuid = z.uuid();

const machineInput = z.object({
  farmId:z.uuid().optional(), code:z.string().trim().min(1).max(60), name:z.string().trim().min(2).max(160),
  machineType:z.string().trim().min(2).max(100), brand:z.string().trim().max(100).optional(), model:z.string().trim().max(100).optional(),
  year:z.number().int().min(1950).max(2100).optional(), fuelType:z.string().trim().max(60).optional(), hourlyCost:z.number().nonnegative().max(1_000_000).optional(),
  hourMeter:z.number().nonnegative().max(100_000_000).optional(), nextMaintenanceHours:z.number().nonnegative().max(100_000_000).optional(), notes:z.string().trim().max(3000).optional(),
});
const machinePatch = z.object({
  status:z.enum(['active','maintenance','inactive']).optional(), hourMeter:z.number().nonnegative().max(100_000_000).optional(),
  odometerKm:z.number().nonnegative().max(100_000_000).optional(), hourlyCost:z.number().nonnegative().max(1_000_000).optional(),
  lastMaintenanceAt:z.iso.datetime({offset:true}).nullable().optional(), nextMaintenanceHours:z.number().nonnegative().max(100_000_000).nullable().optional(), notes:z.string().trim().max(3000).nullable().optional(),
});
const usageInput = z.object({
  machineId:z.uuid(), workOrderId:z.uuid().optional(), fieldId:z.uuid().optional(), seasonId:z.uuid().optional(),
  usageType:z.enum(['operation','maintenance','fuel','breakdown']).default('operation'), startedAt:z.iso.datetime({offset:true}).optional(), finishedAt:z.iso.datetime({offset:true}).optional(),
  startHourMeter:z.number().nonnegative().optional(), endHourMeter:z.number().nonnegative().optional(), fuelLiters:z.number().nonnegative().optional(), fuelUnitCost:z.number().nonnegative().optional(),
  actualCost:z.number().nonnegative().max(1_000_000_000).optional(), notes:z.string().trim().max(3000).optional(),
});
const itemInput = z.object({
  sku:z.string().trim().max(80).optional(), name:z.string().trim().min(2).max(180), category:z.string().trim().min(2).max(100), unit:z.string().trim().min(1).max(40),
  minimumQuantity:z.number().nonnegative().max(1_000_000_000).default(0), averageUnitCost:z.number().nonnegative().max(1_000_000).default(0), supplier:z.string().trim().max(180).optional(), notes:z.string().trim().max(3000).optional(),
});
const movementInput = z.object({
  inventoryItemId:z.uuid(), workOrderId:z.uuid().optional(), fieldId:z.uuid().optional(), seasonId:z.uuid().optional(),
  movementType:z.enum(['in','out','adjustment_in','adjustment_out']), quantity:z.number().positive().max(1_000_000_000), unitCost:z.number().nonnegative().max(1_000_000).optional(),
  supplier:z.string().trim().max(180).optional(), documentNumber:z.string().trim().max(120).optional(), notes:z.string().trim().max(3000).optional(),
});

function qUuid(value:string|undefined){ if(!value)return{value:undefined as string|undefined,invalid:false}; const p=uuid.safeParse(value); return p.success?{value:p.data,invalid:false}:{value:undefined,invalid:true}; }
async function validateFarm(db:Db,orgId:string,farmId?:string){ if(!farmId)return true; const r=await db`SELECT id FROM farms WHERE id=${farmId} AND organization_id=${orgId} LIMIT 1`; return !!r[0]; }
async function validateRefs(db:Db,orgId:string,fieldId?:string,seasonId?:string,workOrderId?:string){
  if(fieldId){const r=await db`SELECT id FROM fields WHERE id=${fieldId} AND organization_id=${orgId} AND active=true LIMIT 1`;if(!r[0])return 'field_not_found';}
  if(seasonId){const r=await db`SELECT id FROM seasons WHERE id=${seasonId} AND organization_id=${orgId} LIMIT 1`;if(!r[0])return 'season_not_found';}
  if(workOrderId){const r=await db`SELECT id FROM work_orders WHERE id=${workOrderId} AND organization_id=${orgId} LIMIT 1`;if(!r[0])return 'work_order_not_found';}
  return null;
}

export function registerAssetsRoutes(app:Hono<AssetsEnv>){
  app.get('/api/v1/machines',async c=>{const farm=qUuid(c.req.query('farmId'));if(farm.invalid)return c.json({error:'invalid_farm'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT m.*,f.name AS farm_name,CASE WHEN m.next_maintenance_hours IS NOT NULL AND m.hour_meter IS NOT NULL AND m.hour_meter>=m.next_maintenance_hours THEN true ELSE false END AS maintenance_due FROM machines m LEFT JOIN farms f ON f.id=m.farm_id WHERE m.organization_id=${orgId} AND (${farm.value??null}::uuid IS NULL OR m.farm_id=${farm.value??null}::uuid) ORDER BY CASE m.status WHEN 'maintenance' THEN 1 WHEN 'active' THEN 2 ELSE 3 END,m.name`;return c.json({data:rows});});

  app.post('/api/v1/machines',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=machineInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;if(!(await validateFarm(db,orgId,b.farmId)))return c.json({error:'farm_not_found'},404);const rows=await db`INSERT INTO machines(organization_id,farm_id,code,name,machine_type,brand,model,year,fuel_type,hourly_cost,hour_meter,next_maintenance_hours,notes) VALUES(${orgId},${b.farmId??null},${b.code},${b.name},${b.machineType},${b.brand??null},${b.model??null},${b.year??null},${b.fuelType??null},${b.hourlyCost??null},${b.hourMeter??null},${b.nextMaintenanceHours??null},${b.notes??null}) RETURNING *`;return c.json({data:rows[0]},201);});

  app.patch('/api/v1/machines/:id',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id')),p=machinePatch.safeParse(await c.req.json());if(!id.success)return c.json({error:'invalid_machine'},400);if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const rows=await db`UPDATE machines SET status=COALESCE(${b.status??null},status),hour_meter=COALESCE(${b.hourMeter??null},hour_meter),odometer_km=COALESCE(${b.odometerKm??null},odometer_km),hourly_cost=COALESCE(${b.hourlyCost??null},hourly_cost),last_maintenance_at=CASE WHEN ${b.lastMaintenanceAt!==undefined}::boolean THEN ${b.lastMaintenanceAt??null}::timestamptz ELSE last_maintenance_at END,next_maintenance_hours=CASE WHEN ${b.nextMaintenanceHours!==undefined}::boolean THEN ${b.nextMaintenanceHours??null}::numeric ELSE next_maintenance_hours END,notes=CASE WHEN ${b.notes!==undefined}::boolean THEN ${b.notes??null} ELSE notes END,updated_at=now() WHERE id=${id.data} AND organization_id=${orgId} RETURNING *`;if(!rows[0])return c.json({error:'machine_not_found'},404);return c.json({data:rows[0]});});

  app.get('/api/v1/machine-usages',async c=>{const season=qUuid(c.req.query('seasonId')),machine=qUuid(c.req.query('machineId'));if(season.invalid||machine.invalid)return c.json({error:'invalid_filter'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT mu.*,m.code AS machine_code,m.name AS machine_name,f.code AS field_code,wo.number AS work_order_number FROM machine_usages mu JOIN machines m ON m.id=mu.machine_id LEFT JOIN fields f ON f.id=mu.field_id LEFT JOIN work_orders wo ON wo.id=mu.work_order_id WHERE mu.organization_id=${orgId} AND (${season.value??null}::uuid IS NULL OR mu.season_id=${season.value??null}::uuid) AND (${machine.value??null}::uuid IS NULL OR mu.machine_id=${machine.value??null}::uuid) ORDER BY mu.created_at DESC LIMIT 500`;return c.json({data:rows});});

  app.post('/api/v1/machine-usages',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=usageInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const machine=await db`SELECT id,hourly_cost FROM machines WHERE id=${b.machineId} AND organization_id=${orgId} AND status<>'inactive' LIMIT 1`;if(!machine[0])return c.json({error:'machine_not_found'},404);const refError=await validateRefs(db,orgId,b.fieldId,b.seasonId,b.workOrderId);if(refError)return c.json({error:refError},404);if(b.endHourMeter!==undefined&&b.startHourMeter!==undefined&&b.endHourMeter<b.startHourMeter)return c.json({error:'invalid_hour_meter'},422);let actualCost=b.actualCost;if(actualCost===undefined&&b.startHourMeter!==undefined&&b.endHourMeter!==undefined&&machine[0].hourly_cost!==null)actualCost=(b.endHourMeter-b.startHourMeter)*Number(machine[0].hourly_cost);if(actualCost===undefined&&b.fuelLiters!==undefined&&b.fuelUnitCost!==undefined)actualCost=b.fuelLiters*b.fuelUnitCost;const rows=await db`INSERT INTO machine_usages(organization_id,machine_id,work_order_id,field_id,season_id,usage_type,started_at,finished_at,start_hour_meter,end_hour_meter,fuel_liters,fuel_unit_cost,actual_cost,notes) VALUES(${orgId},${b.machineId},${b.workOrderId??null},${b.fieldId??null},${b.seasonId??null},${b.usageType},${b.startedAt??null}::timestamptz,${b.finishedAt??null}::timestamptz,${b.startHourMeter??null},${b.endHourMeter??null},${b.fuelLiters??null},${b.fuelUnitCost??null},${actualCost??null},${b.notes??null}) RETURNING *`;const row=rows[0] as any;if(b.endHourMeter!==undefined)await db`UPDATE machines SET hour_meter=GREATEST(COALESCE(hour_meter,0),${b.endHourMeter}),updated_at=now() WHERE id=${b.machineId} AND organization_id=${orgId}`;if(b.usageType==='maintenance')await db`UPDATE machines SET last_maintenance_at=COALESCE(${b.finishedAt??b.startedAt??null}::timestamptz,now()),status='active',updated_at=now() WHERE id=${b.machineId} AND organization_id=${orgId}`;if(actualCost!==undefined&&actualCost>0&&b.seasonId){await db`INSERT INTO cost_entries(organization_id,field_id,season_id,work_order_id,machine_usage_id,category,occurred_on,amount,quantity,unit,notes) VALUES(${orgId},${b.fieldId??null},${b.seasonId},${b.workOrderId??null},${row.id},'Máquinas',(COALESCE(${b.finishedAt??b.startedAt??null}::timestamptz,now()) AT TIME ZONE 'America/Sao_Paulo')::date,${actualCost},${b.endHourMeter!==undefined&&b.startHourMeter!==undefined?b.endHourMeter-b.startHourMeter:null},'h',${`Uso de máquina ${b.machineId}`}) ON CONFLICT(machine_usage_id) WHERE machine_usage_id IS NOT NULL DO UPDATE SET amount=EXCLUDED.amount,quantity=EXCLUDED.quantity,notes=EXCLUDED.notes`;}
    return c.json({data:{...row,actual_cost:actualCost??row.actual_cost}},201);});

  app.get('/api/v1/inventory/items',async c=>{const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT *,CASE WHEN current_quantity<=minimum_quantity THEN true ELSE false END AS low_stock FROM inventory_items WHERE organization_id=${orgId} AND active=true ORDER BY CASE WHEN current_quantity<=minimum_quantity THEN 0 ELSE 1 END,category,name`;return c.json({data:rows});});

  app.post('/api/v1/inventory/items',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=itemInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const rows=await db`INSERT INTO inventory_items(organization_id,sku,name,category,unit,minimum_quantity,average_unit_cost,supplier,notes) VALUES(${orgId},${b.sku??null},${b.name},${b.category},${b.unit},${b.minimumQuantity},${b.averageUnitCost},${b.supplier??null},${b.notes??null}) RETURNING *`;return c.json({data:rows[0]},201);});

  app.get('/api/v1/inventory/movements',async c=>{const season=qUuid(c.req.query('seasonId'));if(season.invalid)return c.json({error:'invalid_season'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT im.*,ii.name AS item_name,ii.sku,ii.unit,f.code AS field_code,wo.number AS work_order_number FROM inventory_movements im JOIN inventory_items ii ON ii.id=im.inventory_item_id LEFT JOIN fields f ON f.id=im.field_id LEFT JOIN work_orders wo ON wo.id=im.work_order_id WHERE im.organization_id=${orgId} AND (${season.value??null}::uuid IS NULL OR im.season_id=${season.value??null}::uuid) ORDER BY im.occurred_at DESC LIMIT 500`;return c.json({data:rows});});

  app.post('/api/v1/inventory/movements',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=movementInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const itemRows=await db`SELECT id FROM inventory_items WHERE id=${b.inventoryItemId} AND organization_id=${orgId} AND active=true LIMIT 1`;if(!itemRows[0])return c.json({error:'inventory_item_not_found'},404);const refError=await validateRefs(db,orgId,b.fieldId,b.seasonId,b.workOrderId);if(refError)return c.json({error:refError},404);let rows:any;try{rows=await db`INSERT INTO inventory_movements(organization_id,inventory_item_id,work_order_id,field_id,season_id,movement_type,quantity,unit_cost,supplier,document_number,notes) VALUES(${orgId},${b.inventoryItemId},${b.workOrderId??null},${b.fieldId??null},${b.seasonId??null},${b.movementType},${b.quantity},${b.unitCost??null},${b.supplier??null},${b.documentNumber??null},${b.notes??null}) RETURNING *`;}catch(error){const message=error instanceof Error?error.message:'';if(message.includes('insufficient_inventory'))return c.json({error:'insufficient_inventory'},409);throw error;}return c.json({data:rows[0]},201);});

  app.get('/api/v1/assets/summary',async c=>{const farm=qUuid(c.req.query('farmId')),season=qUuid(c.req.query('seasonId'));if(farm.invalid||season.invalid)return c.json({error:'invalid_filter'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const [machines]=await db`SELECT COUNT(*) FILTER(WHERE status='active') AS active_machines,COUNT(*) FILTER(WHERE status='maintenance') AS maintenance_machines,COUNT(*) FILTER(WHERE next_maintenance_hours IS NOT NULL AND hour_meter IS NOT NULL AND hour_meter>=next_maintenance_hours) AS maintenance_due FROM machines WHERE organization_id=${orgId} AND (${farm.value??null}::uuid IS NULL OR farm_id=${farm.value??null}::uuid)`;const [inventory]=await db`SELECT COUNT(*) FILTER(WHERE active=true) AS inventory_items,COUNT(*) FILTER(WHERE active=true AND current_quantity<=minimum_quantity) AS low_stock_items,COALESCE(SUM(current_quantity*average_unit_cost) FILTER(WHERE active=true),0) AS inventory_value FROM inventory_items WHERE organization_id=${orgId}`;const [usage]=await db`SELECT COALESCE(SUM(actual_cost),0) AS machine_cost,COALESCE(SUM(fuel_liters),0) AS fuel_liters FROM machine_usages WHERE organization_id=${orgId} AND (${season.value??null}::uuid IS NULL OR season_id=${season.value??null}::uuid)`;return c.json({data:{...(machines??{}),...(inventory??{}),...(usage??{})}});});
}
