import { Hono } from 'hono';
import { neon } from '@neondatabase/serverless';
import { z } from 'zod';

type Role='owner'|'admin'|'manager'|'agronomist'|'operator'|'viewer';
type Env={Bindings:{DATABASE_URL:string};Variables:{authUserId:string;organizationId:string;role:Role}};
type Db=any;
const manageRoles=new Set<Role>(['owner','admin','manager','agronomist']);
const executeRoles=new Set<Role>(['owner','admin','manager','agronomist','operator']);
const uuid=z.uuid();
const COPERNICUS_STAC='https://stac.dataspace.copernicus.eu/v1';
const SENTINEL_COLLECTION='sentinel-2-l2a';

const point=z.object({latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180)}).optional();
const stationInput=z.object({farmId:z.uuid(),fieldId:z.uuid().optional(),code:z.string().trim().min(1).max(80),name:z.string().trim().min(2).max(180),provider:z.string().trim().min(2).max(80).default('internal'),location:point,elevationM:z.number().min(-500).max(10000).optional(),timezone:z.string().trim().min(3).max(80).default('America/Sao_Paulo'),notes:z.string().trim().max(3000).optional()});
const observationInput=z.object({stationId:z.uuid(),observedAt:z.iso.datetime({offset:true}),temperatureC:z.number().min(-100).max(100).optional(),relativeHumidityPct:z.number().min(0).max(100).optional(),rainfallMm:z.number().nonnegative().max(5000).optional(),windSpeedMs:z.number().nonnegative().max(200).optional(),windGustMs:z.number().nonnegative().max(250).optional(),windDirectionDeg:z.number().min(0).max(360).optional(),solarRadiationWM2:z.number().min(0).max(3000).optional(),atmosphericPressureHpa:z.number().min(100).max(1200).optional(),leafWetnessPct:z.number().min(0).max(100).optional(),soilTemperatureC:z.number().min(-100).max(100).optional(),soilMoisturePct:z.number().min(0).max(100).optional(),evapotranspirationMm:z.number().nonnegative().max(1000).optional(),source:z.string().trim().min(2).max(80).default('manual'),rawPayload:z.record(z.string(),z.unknown()).optional()});
const satelliteSearchInput=z.object({fieldId:z.uuid(),days:z.number().int().min(1).max(365).default(45),cloudCoverMax:z.number().min(0).max(100).default(40),limit:z.number().int().min(1).max(25).default(10)});
const importSceneInput=z.object({fieldId:z.uuid(),externalItemId:z.string().trim().min(10).max(300)});
const indexInput=z.object({fieldId:z.uuid(),seasonId:z.uuid().optional(),sceneId:z.uuid().optional(),indexType:z.enum(['ndvi','ndre','evi','ndwi','other']),observedAt:z.iso.datetime({offset:true}),meanValue:z.number().optional(),minValue:z.number().optional(),maxValue:z.number().optional(),stddevValue:z.number().nonnegative().optional(),p10Value:z.number().optional(),p50Value:z.number().optional(),p90Value:z.number().optional(),rasterUrl:z.url().optional(),source:z.string().trim().min(2).max(80).default('processor'),metadata:z.record(z.string(),z.unknown()).optional()});

function qUuid(v:string|undefined){if(!v)return{value:undefined as string|undefined,invalid:false};const p=uuid.safeParse(v);return p.success?{value:p.data,invalid:false}:{value:undefined,invalid:true};}
async function getField(db:Db,orgId:string,fieldId:string){const rows=await db`SELECT f.id,f.farm_id,f.code,ST_AsGeoJSON(f.geometry)::json AS geometry FROM fields f WHERE f.id=${fieldId} AND f.organization_id=${orgId} AND f.active=true LIMIT 1`;return rows[0] as {id:string;farm_id:string;code:string;geometry:any}|undefined;}
function daysAgoIso(days:number){const d=new Date(Date.now()-days*86400000);return d.toISOString().slice(0,10);}
function stacSelfLink(item:any){const links=Array.isArray(item?.links)?item.links:[];return links.find((l:any)=>l?.rel==='self')?.href??null;}
function thumbnail(item:any){return item?.assets?.thumbnail?.href??item?.assets?.rendered_preview?.href??null;}

export function registerClimateSatelliteRoutes(app:Hono<Env>){
  app.get('/api/v1/climate/stations',async c=>{const farm=qUuid(c.req.query('farmId'));if(farm.invalid)return c.json({error:'invalid_farm'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT ws.id,ws.farm_id,ws.field_id,ws.code,ws.name,ws.provider,CASE WHEN ws.location IS NOT NULL THEN ST_AsGeoJSON(ws.location)::json ELSE NULL END AS location,ws.elevation_m,ws.timezone,ws.active,ws.notes,ws.created_at,ws.updated_at,(SELECT MAX(wo.observed_at) FROM weather_observations wo WHERE wo.weather_station_id=ws.id) AS last_observation_at FROM weather_stations ws WHERE ws.organization_id=${orgId} AND ws.active=true AND (${farm.value??null}::uuid IS NULL OR ws.farm_id=${farm.value??null}::uuid) ORDER BY ws.name`;return c.json({data:rows});});

  app.post('/api/v1/climate/stations',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=stationInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const farm=await db`SELECT id FROM farms WHERE id=${b.farmId} AND organization_id=${orgId} LIMIT 1`;if(!farm[0])return c.json({error:'farm_not_found'},404);if(b.fieldId){const field=await getField(db,orgId,b.fieldId);if(!field||field.farm_id!==b.farmId)return c.json({error:'field_not_found'},404);}const rows=await db`INSERT INTO weather_stations(organization_id,farm_id,field_id,code,name,provider,location,elevation_m,timezone,notes) VALUES(${orgId},${b.farmId},${b.fieldId??null},${b.code},${b.name},${b.provider},CASE WHEN ${!!b.location} THEN ST_SetSRID(ST_MakePoint(${b.location?.longitude??0},${b.location?.latitude??0}),4326) ELSE NULL END,${b.elevationM??null},${b.timezone},${b.notes??null}) RETURNING *`;return c.json({data:rows[0]},201);});

  app.get('/api/v1/climate/observations',async c=>{const station=qUuid(c.req.query('stationId')),farm=qUuid(c.req.query('farmId'));if(station.invalid||farm.invalid)return c.json({error:'invalid_filter'},400);const limit=Math.min(Math.max(Number(c.req.query('limit')??200),1),1000);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT wo.*,ws.code AS station_code,ws.name AS station_name FROM weather_observations wo JOIN weather_stations ws ON ws.id=wo.weather_station_id WHERE wo.organization_id=${orgId} AND (${station.value??null}::uuid IS NULL OR wo.weather_station_id=${station.value??null}::uuid) AND (${farm.value??null}::uuid IS NULL OR ws.farm_id=${farm.value??null}::uuid) ORDER BY wo.observed_at DESC LIMIT ${limit}`;return c.json({data:rows});});

  app.post('/api/v1/climate/observations',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=observationInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const station=await db`SELECT id FROM weather_stations WHERE id=${b.stationId} AND organization_id=${orgId} AND active=true LIMIT 1`;if(!station[0])return c.json({error:'station_not_found'},404);const rows=await db`INSERT INTO weather_observations(organization_id,weather_station_id,observed_at,temperature_c,relative_humidity_pct,rainfall_mm,wind_speed_ms,wind_gust_ms,wind_direction_deg,solar_radiation_w_m2,atmospheric_pressure_hpa,leaf_wetness_pct,soil_temperature_c,soil_moisture_pct,evapotranspiration_mm,source,raw_payload) VALUES(${orgId},${b.stationId},${b.observedAt},${b.temperatureC??null},${b.relativeHumidityPct??null},${b.rainfallMm??null},${b.windSpeedMs??null},${b.windGustMs??null},${b.windDirectionDeg??null},${b.solarRadiationWM2??null},${b.atmosphericPressureHpa??null},${b.leafWetnessPct??null},${b.soilTemperatureC??null},${b.soilMoisturePct??null},${b.evapotranspirationMm??null},${b.source},${JSON.stringify(b.rawPayload??{})}::jsonb) ON CONFLICT(weather_station_id,observed_at) DO UPDATE SET temperature_c=EXCLUDED.temperature_c,relative_humidity_pct=EXCLUDED.relative_humidity_pct,rainfall_mm=EXCLUDED.rainfall_mm,wind_speed_ms=EXCLUDED.wind_speed_ms,wind_gust_ms=EXCLUDED.wind_gust_ms,wind_direction_deg=EXCLUDED.wind_direction_deg,solar_radiation_w_m2=EXCLUDED.solar_radiation_w_m2,atmospheric_pressure_hpa=EXCLUDED.atmospheric_pressure_hpa,leaf_wetness_pct=EXCLUDED.leaf_wetness_pct,soil_temperature_c=EXCLUDED.soil_temperature_c,soil_moisture_pct=EXCLUDED.soil_moisture_pct,evapotranspiration_mm=EXCLUDED.evapotranspiration_mm,source=EXCLUDED.source,raw_payload=EXCLUDED.raw_payload RETURNING *`;return c.json({data:rows[0]},201);});

  app.get('/api/v1/climate/summary',async c=>{const farm=qUuid(c.req.query('farmId'));if(farm.invalid||!farm.value)return c.json({error:farm.invalid?'invalid_farm':'missing_farm'},400);const days=Math.min(Math.max(Number(c.req.query('days')??7),1),90);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const latestRows=await db`SELECT wo.*,ws.name AS station_name FROM weather_observations wo JOIN weather_stations ws ON ws.id=wo.weather_station_id WHERE wo.organization_id=${orgId} AND ws.farm_id=${farm.value} ORDER BY wo.observed_at DESC LIMIT 1`;const aggRows=await db`SELECT COUNT(*) AS observations,COUNT(DISTINCT wo.weather_station_id) AS stations,ROUND(AVG(wo.temperature_c),2) AS avg_temperature_c,ROUND(AVG(wo.relative_humidity_pct),2) AS avg_humidity_pct,ROUND(SUM(COALESCE(wo.rainfall_mm,0)),2) AS rainfall_mm,ROUND(MAX(wo.wind_gust_ms),2) AS max_wind_gust_ms,ROUND(SUM(COALESCE(wo.evapotranspiration_mm,0)),2) AS evapotranspiration_mm FROM weather_observations wo JOIN weather_stations ws ON ws.id=wo.weather_station_id WHERE wo.organization_id=${orgId} AND ws.farm_id=${farm.value} AND wo.observed_at>=now()-(${days}::text||' days')::interval`;return c.json({data:{latest:latestRows[0]??null,period_days:days,...(aggRows[0]??{})}});});

  app.post('/api/v1/satellite/search',async c=>{const p=satelliteSearchInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const field=await getField(db,orgId,b.fieldId);if(!field)return c.json({error:'field_not_found'},404);if(!field.geometry)return c.json({error:'field_geometry_required'},409);const now=new Date().toISOString().slice(0,10);const payload={collections:[SENTINEL_COLLECTION],datetime:`${daysAgoIso(b.days)}/${now}`,intersects:field.geometry,query:{'eo:cloud_cover':{lte:b.cloudCoverMax}},sortby:[{field:'properties.datetime',direction:'desc'}],limit:b.limit};let response:Response;try{response=await fetch(`${COPERNICUS_STAC}/search`,{method:'POST',headers:{'Content-Type':'application/json','User-Agent':'Gestor-Cana-360/1.0'},body:JSON.stringify(payload)});}catch{return c.json({error:'satellite_provider_unreachable'},502);}if(!response.ok)return c.json({error:'satellite_provider_error',status:response.status},502);const json=await response.json() as any;const features=Array.isArray(json?.features)?json.features:[];const data=features.map((item:any)=>({external_item_id:item.id,acquired_at:item?.properties?.datetime??item?.properties?.start_datetime??null,cloud_cover_pct:item?.properties?.['eo:cloud_cover']??null,geometry:item?.geometry??null,bbox:item?.bbox??null,thumbnail_url:thumbnail(item),catalogue_url:stacSelfLink(item),platform:item?.properties?.platform??null,collection:item?.collection??SENTINEL_COLLECTION}));return c.json({data,source:'Copernicus Data Space Ecosystem STAC'});});

  app.post('/api/v1/satellite/scenes/import',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=importSceneInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const field=await getField(db,orgId,b.fieldId);if(!field)return c.json({error:'field_not_found'},404);let response:Response;try{response=await fetch(`${COPERNICUS_STAC}/collections/${SENTINEL_COLLECTION}/items/${encodeURIComponent(b.externalItemId)}`,{headers:{'User-Agent':'Gestor-Cana-360/1.0'}});}catch{return c.json({error:'satellite_provider_unreachable'},502);}if(!response.ok)return c.json({error:'satellite_item_not_found'},404);const item=await response.json() as any;const acquired=item?.properties?.datetime??item?.properties?.start_datetime;if(!acquired||!item?.geometry)return c.json({error:'satellite_item_incomplete'},502);const rows=await db`INSERT INTO satellite_scenes(organization_id,farm_id,field_id,provider,collection_id,external_item_id,acquired_at,cloud_cover_pct,footprint,thumbnail_url,catalogue_url,metadata) SELECT ${orgId},${field.farm_id},${field.id},'copernicus',${SENTINEL_COLLECTION},${item.id},${acquired}::timestamptz,${item?.properties?.['eo:cloud_cover']??null},ST_Multi(ST_SetSRID(ST_GeomFromGeoJSON(${JSON.stringify(item.geometry)}),4326)),${thumbnail(item)},${stacSelfLink(item)},${JSON.stringify({platform:item?.properties?.platform??null,gsd:item?.properties?.gsd??null,bbox:item?.bbox??null})}::jsonb WHERE ST_Intersects(ST_SetSRID(ST_GeomFromGeoJSON(${JSON.stringify(item.geometry)}),4326),(SELECT geometry FROM fields WHERE id=${field.id})) ON CONFLICT(organization_id,provider,external_item_id) DO UPDATE SET field_id=EXCLUDED.field_id,farm_id=EXCLUDED.farm_id,cloud_cover_pct=EXCLUDED.cloud_cover_pct,thumbnail_url=EXCLUDED.thumbnail_url,catalogue_url=EXCLUDED.catalogue_url,metadata=EXCLUDED.metadata RETURNING *`;if(!rows[0])return c.json({error:'scene_does_not_intersect_field'},409);return c.json({data:rows[0]},201);});

  app.get('/api/v1/satellite/scenes',async c=>{const field=qUuid(c.req.query('fieldId')),farm=qUuid(c.req.query('farmId'));if(field.invalid||farm.invalid)return c.json({error:'invalid_filter'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT id,farm_id,field_id,provider,collection_id,external_item_id,acquired_at,cloud_cover_pct,thumbnail_url,catalogue_url,metadata,created_at FROM satellite_scenes WHERE organization_id=${orgId} AND (${field.value??null}::uuid IS NULL OR field_id=${field.value??null}::uuid) AND (${farm.value??null}::uuid IS NULL OR farm_id=${farm.value??null}::uuid) ORDER BY acquired_at DESC LIMIT 200`;return c.json({data:rows});});

  app.post('/api/v1/satellite/indices',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=indexInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const field=await getField(db,orgId,b.fieldId);if(!field)return c.json({error:'field_not_found'},404);if(b.seasonId){const s=await db`SELECT id FROM seasons WHERE id=${b.seasonId} AND organization_id=${orgId} LIMIT 1`;if(!s[0])return c.json({error:'season_not_found'},404);}if(b.sceneId){const s=await db`SELECT id FROM satellite_scenes WHERE id=${b.sceneId} AND organization_id=${orgId} AND field_id=${b.fieldId} LIMIT 1`;if(!s[0])return c.json({error:'scene_not_found'},404);}const rows=await db`INSERT INTO vegetation_index_observations(organization_id,satellite_scene_id,farm_id,field_id,season_id,index_type,observed_at,mean_value,min_value,max_value,stddev_value,p10_value,p50_value,p90_value,raster_url,source,metadata) VALUES(${orgId},${b.sceneId??null},${field.farm_id},${field.id},${b.seasonId??null},${b.indexType},${b.observedAt},${b.meanValue??null},${b.minValue??null},${b.maxValue??null},${b.stddevValue??null},${b.p10Value??null},${b.p50Value??null},${b.p90Value??null},${b.rasterUrl??null},${b.source},${JSON.stringify(b.metadata??{})}::jsonb) RETURNING *`;return c.json({data:rows[0]},201);});

  app.get('/api/v1/satellite/indices',async c=>{const field=qUuid(c.req.query('fieldId')),season=qUuid(c.req.query('seasonId'));if(field.invalid||season.invalid||!field.value)return c.json({error:field.invalid?'invalid_field':season.invalid?'invalid_season':'missing_field'},400);const type=c.req.query('type');const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT vio.*,ss.external_item_id,ss.cloud_cover_pct FROM vegetation_index_observations vio LEFT JOIN satellite_scenes ss ON ss.id=vio.satellite_scene_id WHERE vio.organization_id=${orgId} AND vio.field_id=${field.value} AND (${season.value??null}::uuid IS NULL OR vio.season_id=${season.value??null}::uuid) AND (${type??null}::text IS NULL OR vio.index_type=${type??null}::text) ORDER BY vio.observed_at DESC LIMIT 500`;return c.json({data:rows});});

  app.get('/api/v1/satellite/summary',async c=>{const field=qUuid(c.req.query('fieldId'));if(field.invalid||!field.value)return c.json({error:field.invalid?'invalid_field':'missing_field'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const scene=await db`SELECT id,external_item_id,acquired_at,cloud_cover_pct,thumbnail_url FROM satellite_scenes WHERE organization_id=${orgId} AND field_id=${field.value} ORDER BY acquired_at DESC LIMIT 1`;const indices=await db`SELECT DISTINCT ON(index_type) index_type,observed_at,mean_value,min_value,max_value FROM vegetation_index_observations WHERE organization_id=${orgId} AND field_id=${field.value} ORDER BY index_type,observed_at DESC`;const counts=await db`SELECT COUNT(*) AS scenes,ROUND(AVG(cloud_cover_pct),2) AS avg_cloud_cover_pct FROM satellite_scenes WHERE organization_id=${orgId} AND field_id=${field.value}`;return c.json({data:{latest_scene:scene[0]??null,latest_indices:indices,scenes:counts[0]?.scenes??0,avg_cloud_cover_pct:counts[0]?.avg_cloud_cover_pct??null}});});
}
