import { Hono } from 'hono';
import { neon } from '@neondatabase/serverless';
import { z } from 'zod';
import { calculateScenario } from './domain/simulator';

type Role='owner'|'admin'|'manager'|'agronomist'|'operator'|'viewer';
type Env={Bindings:{DATABASE_URL:string;AI_PROVIDER?:string;AI_MODEL?:string;OPENAI_API_KEY?:string;OPENAI_MODEL?:string;AI?:{run(model:string,input:unknown):Promise<unknown>}};Variables:{authUserId:string;organizationId:string;role:Role}};
const simulatorInput=z.object({areaHa:z.number().positive().max(10_000_000),tch:z.number().nonnegative().max(1000),atrKgT:z.number().nonnegative().max(1000),atrPricePerKg:z.number().nonnegative().max(1000),costPerHa:z.number().nonnegative().max(100_000_000),fixedCosts:z.number().nonnegative().max(10_000_000_000).default(0),leaseCost:z.number().nonnegative().max(10_000_000_000).default(0),harvestLossPct:z.number().min(0).max(100).default(0)});
const agronomyInput=z.object({fieldId:z.uuid(),seasonId:z.uuid(),question:z.string().trim().min(3).max(2000)});
function textFromOpenAi(value:any):string{if(typeof value?.output_text==='string')return value.output_text;const chunks:Array<string>=[];for(const out of value?.output??[]){for(const c of out?.content??[]){if(typeof c?.text==='string')chunks.push(c.text);}}return chunks.join('\n').trim();}

export function registerDecisionSupportRoutes(app:Hono<Env>){
  app.post('/api/v1/simulator',async c=>{const p=simulatorInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);return c.json({data:calculateScenario(p.data)});});

  app.post('/api/v1/ai/agronomy',async c=>{const p=agronomyInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const b=p.data,orgId=c.get('organizationId'),db=neon(c.env.DATABASE_URL);const [scope]=await db`SELECT f.id,f.code,f.name,f.area_ha,f.variety,f.cycle,f.farm_id,s.name AS season_name,fs.cut_number,fs.status AS crop_status,fs.expected_tch,fs.expected_atr,fs.expected_tons,fs.planned_planting_on,fs.planned_harvest_on FROM fields f CROSS JOIN seasons s LEFT JOIN field_seasons fs ON fs.field_id=f.id AND fs.season_id=s.id WHERE f.id=${b.fieldId} AND f.organization_id=${orgId} AND f.active=true AND s.id=${b.seasonId} AND s.organization_id=${orgId} LIMIT 1`;if(!scope)return c.json({error:'field_or_season_not_found'},404);
    const [production,soil,pests,weather,vegetation,operations,harvest]=await Promise.all([
      db`SELECT COALESCE(SUM(p.tons),0) AS tons,CASE WHEN SUM(p.tons) FILTER(WHERE p.atr_kg_t IS NOT NULL)>0 THEN ROUND((SUM(p.tons*p.atr_kg_t) FILTER(WHERE p.atr_kg_t IS NOT NULL)/SUM(p.tons) FILTER(WHERE p.atr_kg_t IS NOT NULL))::numeric,2) END AS atr_kg_t,COALESCE(SUM(COALESCE(p.revenue_amount,CASE WHEN p.atr_kg_t IS NOT NULL AND p.atr_price_per_kg IS NOT NULL THEN p.tons*p.atr_kg_t*p.atr_price_per_kg ELSE 0 END)),0) AS revenue,(SELECT COALESCE(SUM(ce.amount),0) FROM cost_entries ce WHERE ce.organization_id=${orgId} AND ce.field_id=${b.fieldId} AND ce.season_id=${b.seasonId}) AS cost FROM production_entries p WHERE p.organization_id=${orgId} AND p.field_id=${b.fieldId} AND p.season_id=${b.seasonId}`,
      db`SELECT sampled_on,depth_from_cm,depth_to_cm,ph,organic_matter_g_dm3,phosphorus_mg_dm3,potassium_mmolc_dm3,calcium_mmolc_dm3,magnesium_mmolc_dm3,cec_mmolc_dm3,base_saturation_pct,clay_pct,sand_pct,silt_pct FROM soil_samples WHERE organization_id=${orgId} AND field_id=${b.fieldId} AND (season_id=${b.seasonId} OR season_id IS NULL) ORDER BY sampled_on DESC LIMIT 5`,
      db`SELECT category,name,observed_on,severity,infestation_pct,infested_area_ha,status FROM pest_occurrences WHERE organization_id=${orgId} AND field_id=${b.fieldId} AND (season_id=${b.seasonId} OR season_id IS NULL) AND status IN('open','monitoring','treated') ORDER BY severity DESC,observed_on DESC LIMIT 10`,
      db`SELECT wo.observed_at,wo.temperature_c,wo.relative_humidity_pct,wo.rain_mm,wo.wind_speed_ms,wo.solar_radiation_wm2,wo.soil_temperature_c,wo.soil_moisture_pct,wo.evapotranspiration_mm,ws.name AS station_name FROM weather_observations wo JOIN weather_stations ws ON ws.id=wo.weather_station_id WHERE wo.organization_id=${orgId} AND (ws.field_id=${b.fieldId} OR (ws.field_id IS NULL AND ws.farm_id=${(scope as any).farm_id})) ORDER BY wo.observed_at DESC LIMIT 24`,
      db`SELECT vio.observed_on,vio.index_type,vio.mean_value,vio.min_value,vio.max_value,vio.stddev_value,ss.cloud_cover_pct FROM vegetation_index_observations vio LEFT JOIN satellite_scenes ss ON ss.id=vio.satellite_scene_id WHERE vio.organization_id=${orgId} AND vio.field_id=${b.fieldId} ORDER BY vio.observed_on DESC,vio.created_at DESC LIMIT 12`,
      db`SELECT number,operation_type,title,status,priority,scheduled_for,started_at,assignee_name,machine_name,product_name,dose,dose_unit,actual_cost FROM work_orders WHERE organization_id=${orgId} AND field_id=${b.fieldId} AND (season_id=${b.seasonId} OR season_id IS NULL) AND status NOT IN('done','cancelled') ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'normal' THEN 2 ELSE 3 END,scheduled_for NULLS LAST LIMIT 15`,
      db`SELECT status,cut_at,loaded_at,departed_at,arrived_mill_at,weighed_at,milled_at,net_tons,atr_kg_t,impurities_pct,fiber_pct FROM harvest_loads WHERE organization_id=${orgId} AND field_id=${b.fieldId} AND season_id=${b.seasonId} ORDER BY created_at DESC LIMIT 10`
    ]);
    const context={field:scope,production:production[0]??null,soil,pests,weather,vegetation,operations,harvest};const system='Você é o copiloto agronômico do Gestor Cana 360 para cana-de-açúcar. Use exclusivamente o CONTEXTO fornecido. Não invente valores, análises laboratoriais, clima, índices, produtos, doses ou diagnósticos ausentes. Diferencie fato observado, inferência e recomendação. Quando faltar dado, diga exatamente o que falta. Não prescreva defensivos ou doses sem dados e validação profissional. Responda em português do Brasil, de forma objetiva, com: Situação; Evidências; Riscos; Próximas ações; Dados faltantes.';const user=`PERGUNTA: ${b.question}\nCONTEXTO: ${JSON.stringify(context)}`;
    if((c.env.AI_PROVIDER??'cloudflare')==='cloudflare'&&c.env.AI){const raw=await c.env.AI.run(c.env.AI_MODEL||'@cf/meta/llama-3.2-3b-instruct',{messages:[{role:'system',content:system},{role:'user',content:user}]}) as any;return c.json({provider:'cloudflare',answer:typeof raw?.response==='string'?raw.response:JSON.stringify(raw),context});}
    if(c.env.AI_PROVIDER==='openai'&&c.env.OPENAI_API_KEY&&c.env.OPENAI_MODEL){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${c.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:c.env.OPENAI_MODEL,instructions:system,input:user})});if(!r.ok)return c.json({error:'ai_provider_error',status:r.status},502);const raw=await r.json();return c.json({provider:'openai',answer:textFromOpenAi(raw)||'Resposta sem texto.',context});}
    return c.json({error:'ai_not_configured'},503);
  });
}
