import { Hono } from 'hono';
import { neon } from '@neondatabase/serverless';
import { z } from 'zod';

type Role = 'owner'|'admin'|'manager'|'agronomist'|'operator'|'viewer';
type HarvestEnv = { Bindings:{DATABASE_URL:string}; Variables:{authUserId:string;organizationId:string;role:Role} };
type Db = any;
const manageRoles = new Set<Role>(['owner','admin','manager','agronomist']);
const executeRoles = new Set<Role>(['owner','admin','manager','agronomist','operator']);
const uuid = z.uuid();

const millInput = z.object({
  name:z.string().trim().min(2).max(180), municipality:z.string().trim().max(120).optional(),
  state:z.string().trim().length(2).transform(v=>v.toUpperCase()).optional(), distanceKm:z.number().nonnegative().max(5000).optional(),
  defaultAtrPricePerKg:z.number().nonnegative().max(100).optional(), notes:z.string().trim().max(3000).optional(),
});
const planInput = z.object({
  farmId:z.uuid(), fieldId:z.uuid(), seasonId:z.uuid(), millId:z.uuid().optional(),
  plannedStart:z.iso.date().optional(), plannedEnd:z.iso.date().optional(),
  priority:z.enum(['low','normal','high','critical']).default('normal'), expectedTons:z.number().positive().max(1_000_000).optional(),
  notes:z.string().trim().max(3000).optional(),
});
const planPatch = z.object({
  millId:z.uuid().nullable().optional(), plannedStart:z.iso.date().nullable().optional(), plannedEnd:z.iso.date().nullable().optional(),
  priority:z.enum(['low','normal','high','critical']).optional(), expectedTons:z.number().positive().max(1_000_000).nullable().optional(),
  status:z.enum(['planned','ready','harvesting','completed','cancelled']).optional(), notes:z.string().trim().max(3000).nullable().optional(),
});
const loadInput = z.object({
  harvestPlanId:z.uuid().optional(), farmId:z.uuid(), fieldId:z.uuid(), seasonId:z.uuid(), millId:z.uuid().optional(),
  ticketNumber:z.string().trim().max(100).optional(), vehiclePlate:z.string().trim().max(30).optional(), driverName:z.string().trim().max(160).optional(),
  cutAt:z.iso.datetime({offset:true}).optional(), notes:z.string().trim().max(3000).optional(),
});
const deliverInput = z.object({
  ticketNumber:z.string().trim().max(100).optional(), netTons:z.number().positive().max(500), atrKgT:z.number().positive().max(500).optional(),
  atrPricePerKg:z.number().nonnegative().max(100).optional(), revenueAmount:z.number().nonnegative().max(1_000_000_000).optional(),
  impuritiesPct:z.number().min(0).max(100).optional(), fiberPct:z.number().min(0).max(100).optional(),
  weighedAt:z.iso.datetime({offset:true}).optional(), milledAt:z.iso.datetime({offset:true}).optional(), notes:z.string().trim().max(3000).optional(),
});

function queryUuid(value:string|undefined){ if(!value)return{value:undefined as string|undefined,invalid:false}; const p=uuid.safeParse(value); return p.success?{value:p.data,invalid:false}:{value:undefined,invalid:true}; }
async function validateScope(db:Db,orgId:string,seasonId:string,farmId:string,fieldId:string){
  const rows=await db`SELECT f.id,f.farm_id FROM fields f JOIN seasons s ON s.id=${seasonId} AND s.organization_id=${orgId} WHERE f.id=${fieldId} AND f.organization_id=${orgId} AND f.active=true LIMIT 1`;
  const row=rows[0] as {farm_id?:string}|undefined; if(!row?.farm_id)return 'scope_not_found'; if(row.farm_id!==farmId)return 'field_farm_mismatch'; return null;
}
async function validateMill(db:Db,orgId:string,millId?:string){if(!millId)return null;const rows=await db`SELECT id FROM mills WHERE id=${millId} AND organization_id=${orgId} AND active=true LIMIT 1`;return rows[0]?null:'mill_not_found';}

export function registerHarvestRoutes(app:Hono<HarvestEnv>){
  app.get('/api/v1/mills',async c=>{const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT id,name,municipality,state,distance_km,default_atr_price_per_kg,active,notes,created_at,updated_at FROM mills WHERE organization_id=${orgId} AND active=true ORDER BY name`;return c.json({data:rows});});

  app.post('/api/v1/mills',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=millInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const rows=await db`INSERT INTO mills(organization_id,name,municipality,state,distance_km,default_atr_price_per_kg,notes) VALUES(${orgId},${b.name},${b.municipality??null},${b.state??null},${b.distanceKm??null},${b.defaultAtrPricePerKg??null},${b.notes??null}) RETURNING *`;return c.json({data:rows[0]},201);});

  app.patch('/api/v1/mills/:id',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id')),p=millInput.partial().safeParse(await c.req.json());if(!id.success)return c.json({error:'invalid_mill'},400);if(!p.success)return c.json({error:'validation_error'},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const rows=await db`UPDATE mills SET name=COALESCE(${b.name??null},name),municipality=COALESCE(${b.municipality??null},municipality),state=COALESCE(${b.state??null},state),distance_km=COALESCE(${b.distanceKm??null},distance_km),default_atr_price_per_kg=COALESCE(${b.defaultAtrPricePerKg??null},default_atr_price_per_kg),notes=COALESCE(${b.notes??null},notes) WHERE id=${id.data} AND organization_id=${orgId} RETURNING *`;if(!rows[0])return c.json({error:'mill_not_found'},404);return c.json({data:rows[0]});});

  app.get('/api/v1/harvest/plans',async c=>{const season=queryUuid(c.req.query('seasonId')),farm=queryUuid(c.req.query('farmId'));if(!season.value)return c.json({error:season.invalid?'invalid_season':'missing_season'},400);if(farm.invalid)return c.json({error:'invalid_farm'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT hp.*,f.name AS farm_name,fld.code AS field_code,fld.area_ha,fld.variety,m.name AS mill_name,COALESCE((SELECT SUM(hl.net_tons) FROM harvest_loads hl WHERE hl.harvest_plan_id=hp.id AND hl.status='delivered'),0) AS delivered_tons FROM harvest_plans hp JOIN farms f ON f.id=hp.farm_id JOIN fields fld ON fld.id=hp.field_id LEFT JOIN mills m ON m.id=hp.mill_id WHERE hp.organization_id=${orgId} AND hp.season_id=${season.value} AND (${farm.value??null}::uuid IS NULL OR hp.farm_id=${farm.value??null}::uuid) ORDER BY CASE hp.priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'normal' THEN 3 ELSE 4 END,hp.planned_start NULLS LAST,hp.created_at`;return c.json({data:rows});});

  app.post('/api/v1/harvest/plans',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=planInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const scope=await validateScope(db,orgId,b.seasonId,b.farmId,b.fieldId);if(scope)return c.json({error:scope},404);const millError=await validateMill(db,orgId,b.millId);if(millError)return c.json({error:millError},404);const rows=await db`INSERT INTO harvest_plans(organization_id,farm_id,field_id,season_id,mill_id,planned_start,planned_end,priority,expected_tons,notes) VALUES(${orgId},${b.farmId},${b.fieldId},${b.seasonId},${b.millId??null},${b.plannedStart??null},${b.plannedEnd??null},${b.priority},${b.expectedTons??null},${b.notes??null}) RETURNING *`;return c.json({data:rows[0]},201);});

  app.patch('/api/v1/harvest/plans/:id',async c=>{if(!manageRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id')),p=planPatch.safeParse(await c.req.json());if(!id.success)return c.json({error:'invalid_plan'},400);if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;if(b.millId){const e=await validateMill(db,orgId,b.millId);if(e)return c.json({error:e},404);}const rows=await db`UPDATE harvest_plans SET mill_id=CASE WHEN ${b.millId!==undefined}::boolean THEN ${b.millId??null}::uuid ELSE mill_id END,planned_start=CASE WHEN ${b.plannedStart!==undefined}::boolean THEN ${b.plannedStart??null}::date ELSE planned_start END,planned_end=CASE WHEN ${b.plannedEnd!==undefined}::boolean THEN ${b.plannedEnd??null}::date ELSE planned_end END,priority=COALESCE(${b.priority??null},priority),expected_tons=CASE WHEN ${b.expectedTons!==undefined}::boolean THEN ${b.expectedTons??null}::numeric ELSE expected_tons END,status=COALESCE(${b.status??null},status),notes=CASE WHEN ${b.notes!==undefined}::boolean THEN ${b.notes??null} ELSE notes END WHERE id=${id.data} AND organization_id=${orgId} RETURNING *`;if(!rows[0])return c.json({error:'plan_not_found'},404);return c.json({data:rows[0]});});

  app.get('/api/v1/harvest/loads',async c=>{const season=queryUuid(c.req.query('seasonId')),farm=queryUuid(c.req.query('farmId'));if(!season.value)return c.json({error:season.invalid?'invalid_season':'missing_season'},400);if(farm.invalid)return c.json({error:'invalid_farm'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT hl.*,fld.code AS field_code,m.name AS mill_name,CASE WHEN hl.cut_at IS NOT NULL AND hl.loaded_at IS NOT NULL THEN ROUND(EXTRACT(EPOCH FROM(hl.loaded_at-hl.cut_at))/60) END AS cut_to_load_minutes,CASE WHEN hl.loaded_at IS NOT NULL AND hl.arrived_mill_at IS NOT NULL THEN ROUND(EXTRACT(EPOCH FROM(hl.arrived_mill_at-hl.loaded_at))/60) END AS load_to_mill_minutes,CASE WHEN hl.cut_at IS NOT NULL AND COALESCE(hl.milled_at,hl.arrived_mill_at) IS NOT NULL THEN ROUND(EXTRACT(EPOCH FROM(COALESCE(hl.milled_at,hl.arrived_mill_at)-hl.cut_at))/60) END AS ctt_total_minutes FROM harvest_loads hl JOIN fields fld ON fld.id=hl.field_id LEFT JOIN mills m ON m.id=hl.mill_id WHERE hl.organization_id=${orgId} AND hl.season_id=${season.value} AND (${farm.value??null}::uuid IS NULL OR hl.farm_id=${farm.value??null}::uuid) ORDER BY hl.created_at DESC LIMIT 500`;return c.json({data:rows});});

  app.post('/api/v1/harvest/loads',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=loadInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const scope=await validateScope(db,orgId,b.seasonId,b.farmId,b.fieldId);if(scope)return c.json({error:scope},404);const millError=await validateMill(db,orgId,b.millId);if(millError)return c.json({error:millError},404);if(b.harvestPlanId){const plans=await db`SELECT id FROM harvest_plans WHERE id=${b.harvestPlanId} AND organization_id=${orgId} AND field_id=${b.fieldId} AND season_id=${b.seasonId} LIMIT 1`;if(!plans[0])return c.json({error:'plan_not_found'},404);}const rows=await db`INSERT INTO harvest_loads(organization_id,harvest_plan_id,farm_id,field_id,season_id,mill_id,ticket_number,vehicle_plate,driver_name,status,cut_at,notes) VALUES(${orgId},${b.harvestPlanId??null},${b.farmId},${b.fieldId},${b.seasonId},${b.millId??null},${b.ticketNumber??null},${b.vehiclePlate??null},${b.driverName??null},'cutting',${b.cutAt??null}::timestamptz,${b.notes??null}) RETURNING *`;if(b.harvestPlanId)await db`UPDATE harvest_plans SET status='harvesting' WHERE id=${b.harvestPlanId} AND organization_id=${orgId} AND status IN('planned','ready')`;return c.json({data:rows[0]},201);});

  app.post('/api/v1/harvest/loads/:id/loaded',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id'));if(!id.success)return c.json({error:'invalid_load'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`UPDATE harvest_loads SET status='loaded',loaded_at=now() WHERE id=${id.data} AND organization_id=${orgId} AND status='cutting' RETURNING *`;if(!rows[0])return c.json({error:'invalid_status_transition'},409);return c.json({data:rows[0]});});
  app.post('/api/v1/harvest/loads/:id/depart',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id'));if(!id.success)return c.json({error:'invalid_load'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`UPDATE harvest_loads SET status='in_transit',departed_at=now() WHERE id=${id.data} AND organization_id=${orgId} AND status='loaded' RETURNING *`;if(!rows[0])return c.json({error:'invalid_status_transition'},409);return c.json({data:rows[0]});});
  app.post('/api/v1/harvest/loads/:id/arrive',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id'));if(!id.success)return c.json({error:'invalid_load'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`UPDATE harvest_loads SET status='arrived',arrived_mill_at=now() WHERE id=${id.data} AND organization_id=${orgId} AND status='in_transit' RETURNING *`;if(!rows[0])return c.json({error:'invalid_status_transition'},409);return c.json({data:rows[0]});});

  app.post('/api/v1/harvest/loads/:id/deliver',async c=>{if(!executeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id')),p=deliverInput.safeParse(await c.req.json());if(!id.success)return c.json({error:'invalid_load'},400);if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const rows=await db`UPDATE harvest_loads SET status='delivered',ticket_number=COALESCE(${b.ticketNumber??null},ticket_number),weighed_at=COALESCE(${b.weighedAt??null}::timestamptz,now()),milled_at=${b.milledAt??null}::timestamptz,net_tons=${b.netTons},atr_kg_t=${b.atrKgT??null},atr_price_per_kg=${b.atrPricePerKg??null},revenue_amount=${b.revenueAmount??null},impurities_pct=${b.impuritiesPct??null},fiber_pct=${b.fiberPct??null},notes=COALESCE(${b.notes??null},notes) WHERE id=${id.data} AND organization_id=${orgId} AND status IN('arrived','in_transit','loaded') RETURNING *`;const row=rows[0] as any;if(!row)return c.json({error:'invalid_status_transition'},409);await db`INSERT INTO production_entries(organization_id,field_id,season_id,harvest_load_id,occurred_on,tons,atr_kg_t,atr_price_per_kg,revenue_amount,source,notes) VALUES(${orgId},${row.field_id},${row.season_id},${row.id},(COALESCE(row.weighed_at,now()) AT TIME ZONE 'America/Sao_Paulo')::date,${row.net_tons},${row.atr_kg_t},${row.atr_price_per_kg},${row.revenue_amount},'harvest_load',${`Carga ${row.ticket_number??row.id}`}) ON CONFLICT(harvest_load_id) WHERE harvest_load_id IS NOT NULL DO UPDATE SET occurred_on=EXCLUDED.occurred_on,tons=EXCLUDED.tons,atr_kg_t=EXCLUDED.atr_kg_t,atr_price_per_kg=EXCLUDED.atr_price_per_kg,revenue_amount=EXCLUDED.revenue_amount,notes=EXCLUDED.notes`;return c.json({data:row});});

  app.get('/api/v1/harvest/summary',async c=>{const season=queryUuid(c.req.query('seasonId')),farm=queryUuid(c.req.query('farmId'));if(!season.value)return c.json({error:season.invalid?'invalid_season':'missing_season'},400);if(farm.invalid)return c.json({error:'invalid_farm'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const [row]=await db`SELECT COUNT(*) FILTER(WHERE status NOT IN('delivered','rejected','cancelled')) AS active_loads,COUNT(*) FILTER(WHERE status='delivered') AS delivered_loads,COALESCE(SUM(net_tons) FILTER(WHERE status='delivered'),0) AS delivered_tons,CASE WHEN COALESCE(SUM(net_tons) FILTER(WHERE status='delivered' AND atr_kg_t IS NOT NULL),0)>0 THEN ROUND((SUM(net_tons*atr_kg_t) FILTER(WHERE status='delivered' AND atr_kg_t IS NOT NULL)/SUM(net_tons) FILTER(WHERE status='delivered' AND atr_kg_t IS NOT NULL))::numeric,2) END AS atr_kg_t,ROUND(AVG(EXTRACT(EPOCH FROM(COALESCE(milled_at,arrived_mill_at)-cut_at))/60) FILTER(WHERE cut_at IS NOT NULL AND COALESCE(milled_at,arrived_mill_at) IS NOT NULL)) AS avg_ctt_minutes,COUNT(*) FILTER(WHERE cut_at IS NOT NULL AND COALESCE(milled_at,arrived_mill_at) IS NULL AND now()-cut_at>interval '180 minutes' AND status NOT IN('delivered','rejected','cancelled')) AS ctt_alerts,COALESCE(SUM(COALESCE(revenue_amount,CASE WHEN net_tons IS NOT NULL AND atr_kg_t IS NOT NULL AND atr_price_per_kg IS NOT NULL THEN net_tons*atr_kg_t*atr_price_per_kg ELSE 0 END)) FILTER(WHERE status='delivered'),0) AS revenue FROM harvest_loads WHERE organization_id=${orgId} AND season_id=${season.value} AND (${farm.value??null}::uuid IS NULL OR farm_id=${farm.value??null}::uuid)`;const [plans]=await db`SELECT COUNT(*) FILTER(WHERE status IN('planned','ready')) AS queued_plans,COUNT(*) FILTER(WHERE status='harvesting') AS harvesting_plans,COALESCE(SUM(expected_tons) FILTER(WHERE status NOT IN('completed','cancelled')),0) AS queued_tons FROM harvest_plans WHERE organization_id=${orgId} AND season_id=${season.value} AND (${farm.value??null}::uuid IS NULL OR farm_id=${farm.value??null}::uuid)`;return c.json({data:{...(row??{}),...(plans??{})}});});

  app.get('/api/v1/harvest/mills-performance',async c=>{const season=queryUuid(c.req.query('seasonId'));if(!season.value)return c.json({error:season.invalid?'invalid_season':'missing_season'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT m.id,m.name,m.municipality,m.state,m.distance_km,COUNT(hl.id) FILTER(WHERE hl.status='delivered') AS loads,COALESCE(SUM(hl.net_tons) FILTER(WHERE hl.status='delivered'),0) AS tons,CASE WHEN COALESCE(SUM(hl.net_tons) FILTER(WHERE hl.status='delivered' AND hl.atr_kg_t IS NOT NULL),0)>0 THEN ROUND((SUM(hl.net_tons*hl.atr_kg_t) FILTER(WHERE hl.status='delivered' AND hl.atr_kg_t IS NOT NULL)/SUM(hl.net_tons) FILTER(WHERE hl.status='delivered' AND hl.atr_kg_t IS NOT NULL))::numeric,2) END AS atr_kg_t,ROUND(AVG(EXTRACT(EPOCH FROM(COALESCE(hl.milled_at,hl.arrived_mill_at)-hl.cut_at))/60) FILTER(WHERE hl.cut_at IS NOT NULL AND COALESCE(hl.milled_at,hl.arrived_mill_at) IS NOT NULL)) AS avg_ctt_minutes,COALESCE(SUM(COALESCE(hl.revenue_amount,CASE WHEN hl.net_tons IS NOT NULL AND hl.atr_kg_t IS NOT NULL AND hl.atr_price_per_kg IS NOT NULL THEN hl.net_tons*hl.atr_kg_t*hl.atr_price_per_kg ELSE 0 END)) FILTER(WHERE hl.status='delivered'),0) AS revenue FROM mills m LEFT JOIN harvest_loads hl ON hl.mill_id=m.id AND hl.season_id=${season.value} AND hl.organization_id=${orgId} WHERE m.organization_id=${orgId} AND m.active=true GROUP BY m.id ORDER BY tons DESC,m.name`;return c.json({data:rows});});
}
