import { Hono } from 'hono';
import { neon } from '@neondatabase/serverless';
import { z } from 'zod';

type Role='owner'|'admin'|'manager'|'agronomist'|'operator'|'viewer';
type Env={Bindings:{DATABASE_URL:string};Variables:{authUserId:string;organizationId:string;role:Role}};
type Db=any;
const uuid=z.uuid();
const planningRoles=new Set<Role>(['owner','admin','manager','agronomist']);
const financeRoles=new Set<Role>(['owner','admin','manager']);

const planInput=z.object({
  farmId:z.uuid(),fieldId:z.uuid(),seasonId:z.uuid(),variety:z.string().trim().max(100).optional(),cutNumber:z.number().int().min(0).max(30).optional(),
  plantedOn:z.iso.date().nullable().optional(),expectedHarvestOn:z.iso.date().nullable().optional(),plannedPlantingOn:z.iso.date().nullable().optional(),plannedHarvestOn:z.iso.date().nullable().optional(),
  rowSpacingM:z.number().positive().max(10).nullable().optional(),expectedTch:z.number().nonnegative().max(1000).nullable().optional(),expectedAtr:z.number().nonnegative().max(1000).nullable().optional(),
  expectedTons:z.number().nonnegative().max(100_000_000).nullable().optional(),budgetAmount:z.number().nonnegative().max(10_000_000_000).nullable().optional(),expectedRevenueAmount:z.number().nonnegative().max(10_000_000_000).nullable().optional(),
  plantingDirectionDeg:z.number().min(0).max(360).nullable().optional(),status:z.enum(['planned','growing','ready','harvesting','harvested','closed']).default('planned'),notes:z.string().trim().max(4000).nullable().optional(),
});
const lineGeometry=z.object({type:z.enum(['LineString','MultiLineString']),coordinates:z.array(z.any())});
const designInput=z.object({farmId:z.uuid(),fieldId:z.uuid(),seasonId:z.uuid().optional(),featureType:z.enum(['planting_line','ab_line','contour_line','access','drainage','other']),name:z.string().trim().max(160).optional(),geometry:lineGeometry,spacingM:z.number().positive().max(100).optional(),notes:z.string().trim().max(3000).optional()});
const leaseInput=z.object({farmId:z.uuid(),fieldId:z.uuid().optional(),contractNumber:z.string().trim().max(120).optional(),lessorName:z.string().trim().min(2).max(180),startsOn:z.iso.date(),endsOn:z.iso.date(),areaHa:z.number().nonnegative().max(10_000_000).optional(),calculationBasis:z.enum(['fixed','per_ha','revenue_share','tons_equivalent']).default('fixed'),annualAmount:z.number().nonnegative().max(10_000_000_000).optional(),pricePerHa:z.number().nonnegative().max(100_000_000).optional(),revenueSharePct:z.number().min(0).max(100).optional(),tonsEquivalent:z.number().nonnegative().max(100_000_000).optional(),status:z.enum(['draft','active','closed','cancelled']).default('active'),notes:z.string().trim().max(4000).optional()}).refine(v=>v.endsOn>=v.startsOn,{message:'ends_on_before_starts_on'});
const paymentInput=z.object({seasonId:z.uuid(),dueOn:z.iso.date(),amount:z.number().nonnegative().max(10_000_000_000),documentNumber:z.string().trim().max(120).optional(),notes:z.string().trim().max(3000).optional()});
const payInput=z.object({paidOn:z.iso.date().optional(),documentNumber:z.string().trim().max(120).optional(),notes:z.string().trim().max(3000).optional()});

function qUuid(v:string|undefined){if(!v)return{value:undefined as string|undefined,invalid:false};const p=uuid.safeParse(v);return p.success?{value:p.data,invalid:false}:{value:undefined,invalid:true};}
async function validateScope(db:Db,orgId:string,farmId:string,fieldId?:string,seasonId?:string){const farm=await db`SELECT id FROM farms WHERE id=${farmId} AND organization_id=${orgId} LIMIT 1`;if(!farm[0])return'farm_not_found';if(fieldId){const field=await db`SELECT id FROM fields WHERE id=${fieldId} AND farm_id=${farmId} AND organization_id=${orgId} AND active=true LIMIT 1`;if(!field[0])return'field_not_found';}if(seasonId){const season=await db`SELECT id FROM seasons WHERE id=${seasonId} AND organization_id=${orgId} LIMIT 1`;if(!season[0])return'season_not_found';}return null;}

export function registerPlanningLeaseRoutes(app:Hono<Env>){
  app.get('/api/v1/planning',async c=>{const farm=qUuid(c.req.query('farmId')),season=qUuid(c.req.query('seasonId'));if(farm.invalid||season.invalid||!season.value)return c.json({error:'invalid_or_missing_season'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT fs.*,f.code AS field_code,f.name AS field_name,f.area_ha,f.variety AS field_variety,COALESCE(fs.expected_tons,CASE WHEN fs.expected_tch IS NOT NULL THEN f.area_ha*fs.expected_tch END) AS projected_tons,CASE WHEN fs.expected_tch IS NOT NULL AND fs.expected_atr IS NOT NULL THEN ROUND((fs.expected_tch*fs.expected_atr/1000)::numeric,3) END AS expected_tah FROM field_seasons fs JOIN fields f ON f.id=fs.field_id WHERE fs.organization_id=${orgId} AND fs.season_id=${season.value} AND f.active=true AND (${farm.value??null}::uuid IS NULL OR f.farm_id=${farm.value??null}::uuid) ORDER BY f.code`;return c.json({data:rows});});

  app.get('/api/v1/planning/summary',async c=>{const farm=qUuid(c.req.query('farmId')),season=qUuid(c.req.query('seasonId'));if(farm.invalid||season.invalid||!season.value)return c.json({error:'invalid_or_missing_season'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const [row]=await db`SELECT COUNT(fs.id) AS planned_fields,COALESCE(SUM(f.area_ha),0) AS planned_area_ha,COALESCE(SUM(COALESCE(fs.expected_tons,CASE WHEN fs.expected_tch IS NOT NULL THEN f.area_ha*fs.expected_tch ELSE 0 END)),0) AS expected_tons,ROUND(AVG(fs.expected_tch),2) AS avg_expected_tch,ROUND(AVG(fs.expected_atr),2) AS avg_expected_atr,COALESCE(SUM(fs.budget_amount),0) AS budget_amount,COALESCE(SUM(fs.expected_revenue_amount),0) AS expected_revenue_amount,COALESCE(SUM(fs.expected_revenue_amount),0)-COALESCE(SUM(fs.budget_amount),0) AS projected_margin FROM field_seasons fs JOIN fields f ON f.id=fs.field_id WHERE fs.organization_id=${orgId} AND fs.season_id=${season.value} AND f.active=true AND (${farm.value??null}::uuid IS NULL OR f.farm_id=${farm.value??null}::uuid)`;return c.json({data:row??{}});});

  app.put('/api/v1/planning/:fieldId',async c=>{if(!planningRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const fieldId=uuid.safeParse(c.req.param('fieldId')),p=planInput.safeParse(await c.req.json());if(!fieldId.success)return c.json({error:'invalid_field'},400);if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;if(fieldId.data!==b.fieldId)return c.json({error:'field_id_mismatch'},422);const scope=await validateScope(db,orgId,b.farmId,b.fieldId,b.seasonId);if(scope)return c.json({error:scope},404);const rows=await db`INSERT INTO field_seasons(organization_id,field_id,season_id,variety,cut_number,planted_on,expected_harvest_on,planned_planting_on,planned_harvest_on,row_spacing_m,expected_tch,expected_atr,expected_tons,budget_amount,expected_revenue_amount,planting_direction_deg,status,notes) VALUES(${orgId},${b.fieldId},${b.seasonId},${b.variety??null},${b.cutNumber??null},${b.plantedOn??null}::date,${b.expectedHarvestOn??null}::date,${b.plannedPlantingOn??null}::date,${b.plannedHarvestOn??null}::date,${b.rowSpacingM??null},${b.expectedTch??null},${b.expectedAtr??null},${b.expectedTons??null},${b.budgetAmount??null},${b.expectedRevenueAmount??null},${b.plantingDirectionDeg??null},${b.status},${b.notes??null}) ON CONFLICT(field_id,season_id) DO UPDATE SET variety=EXCLUDED.variety,cut_number=EXCLUDED.cut_number,planted_on=EXCLUDED.planted_on,expected_harvest_on=EXCLUDED.expected_harvest_on,planned_planting_on=EXCLUDED.planned_planting_on,planned_harvest_on=EXCLUDED.planned_harvest_on,row_spacing_m=EXCLUDED.row_spacing_m,expected_tch=EXCLUDED.expected_tch,expected_atr=EXCLUDED.expected_atr,expected_tons=EXCLUDED.expected_tons,budget_amount=EXCLUDED.budget_amount,expected_revenue_amount=EXCLUDED.expected_revenue_amount,planting_direction_deg=EXCLUDED.planting_direction_deg,status=EXCLUDED.status,notes=EXCLUDED.notes,updated_at=now() RETURNING *`;return c.json({data:rows[0]});});

  app.get('/api/v1/planning/design-features',async c=>{const field=qUuid(c.req.query('fieldId')),season=qUuid(c.req.query('seasonId'));if(field.invalid||season.invalid||!field.value)return c.json({error:'invalid_or_missing_field'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT id,farm_id,field_id,season_id,feature_type,name,ST_AsGeoJSON(geometry)::json AS geometry,spacing_m,length_m,notes,created_at,updated_at FROM cultivation_design_features WHERE organization_id=${orgId} AND field_id=${field.value} AND (${season.value??null}::uuid IS NULL OR season_id=${season.value??null}::uuid) ORDER BY feature_type,name NULLS LAST,created_at`;return c.json({data:rows});});

  app.post('/api/v1/planning/design-features',async c=>{if(!planningRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=designInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const scope=await validateScope(db,orgId,b.farmId,b.fieldId,b.seasonId);if(scope)return c.json({error:scope},404);const geojson=JSON.stringify(b.geometry);const check=await db`SELECT ST_Intersects(f.geometry,ST_Multi(ST_Force2D(ST_SetSRID(ST_GeomFromGeoJSON(${geojson}),4326)))) AS intersects FROM fields f WHERE f.id=${b.fieldId} AND f.organization_id=${orgId} AND f.geometry IS NOT NULL`;if(!check[0]?.intersects)return c.json({error:'design_geometry_outside_field'},422);const rows=await db`INSERT INTO cultivation_design_features(organization_id,farm_id,field_id,season_id,feature_type,name,geometry,spacing_m,length_m,notes) VALUES(${orgId},${b.farmId},${b.fieldId},${b.seasonId??null},${b.featureType},${b.name??null},ST_Multi(ST_Force2D(ST_SetSRID(ST_GeomFromGeoJSON(${geojson}),4326))),${b.spacingM??null},ST_Length(ST_Multi(ST_Force2D(ST_SetSRID(ST_GeomFromGeoJSON(${geojson}),4326)))::geography),${b.notes??null}) RETURNING id,farm_id,field_id,season_id,feature_type,name,ST_AsGeoJSON(geometry)::json AS geometry,spacing_m,length_m,notes`;return c.json({data:rows[0]},201);});

  app.get('/api/v1/leases',async c=>{const farm=qUuid(c.req.query('farmId'));if(farm.invalid)return c.json({error:'invalid_farm'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT l.*,f.name AS farm_name,fd.code AS field_code,(SELECT MIN(lp.due_on) FROM lease_payments lp WHERE lp.lease_id=l.id AND lp.status='planned') AS next_due_on,(SELECT COALESCE(SUM(lp.amount),0) FROM lease_payments lp WHERE lp.lease_id=l.id AND lp.status='planned') AS planned_amount,(SELECT COALESCE(SUM(lp.amount),0) FROM lease_payments lp WHERE lp.lease_id=l.id AND lp.status='paid') AS paid_amount FROM leases l JOIN farms f ON f.id=l.farm_id LEFT JOIN fields fd ON fd.id=l.field_id WHERE l.organization_id=${orgId} AND (${farm.value??null}::uuid IS NULL OR l.farm_id=${farm.value??null}::uuid) ORDER BY CASE l.status WHEN 'active' THEN 1 WHEN 'draft' THEN 2 WHEN 'closed' THEN 3 ELSE 4 END,l.ends_on`;return c.json({data:rows});});

  app.get('/api/v1/leases/summary',async c=>{const farm=qUuid(c.req.query('farmId')),season=qUuid(c.req.query('seasonId'));if(farm.invalid||season.invalid)return c.json({error:'invalid_filter'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const [contracts]=await db`SELECT COUNT(*) FILTER(WHERE status='active') AS active_contracts,COALESCE(SUM(area_ha) FILTER(WHERE status='active'),0) AS leased_area_ha FROM leases WHERE organization_id=${orgId} AND (${farm.value??null}::uuid IS NULL OR farm_id=${farm.value??null}::uuid)`;const [payments]=await db`SELECT COALESCE(SUM(lp.amount) FILTER(WHERE lp.status='paid'),0) AS paid_amount,COALESCE(SUM(lp.amount) FILTER(WHERE lp.status='planned'),0) AS planned_amount,COALESCE(SUM(lp.amount) FILTER(WHERE lp.status='planned' AND lp.due_on<CURRENT_DATE),0) AS overdue_amount,COUNT(*) FILTER(WHERE lp.status='planned' AND lp.due_on<CURRENT_DATE) AS overdue_payments FROM lease_payments lp JOIN leases l ON l.id=lp.lease_id WHERE lp.organization_id=${orgId} AND (${farm.value??null}::uuid IS NULL OR l.farm_id=${farm.value??null}::uuid) AND (${season.value??null}::uuid IS NULL OR lp.season_id=${season.value??null}::uuid)`;return c.json({data:{...(contracts??{}),...(payments??{})}});});

  app.post('/api/v1/leases',async c=>{if(!financeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const p=leaseInput.safeParse(await c.req.json());if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const scope=await validateScope(db,orgId,b.farmId,b.fieldId);if(scope)return c.json({error:scope},404);const rows=await db`INSERT INTO leases(organization_id,farm_id,field_id,contract_number,lessor_name,starts_on,ends_on,area_ha,calculation_basis,annual_amount,price_per_ha,revenue_share_pct,tons_equivalent,status,notes) VALUES(${orgId},${b.farmId},${b.fieldId??null},${b.contractNumber??null},${b.lessorName},${b.startsOn},${b.endsOn},${b.areaHa??null},${b.calculationBasis},${b.annualAmount??null},${b.pricePerHa??null},${b.revenueSharePct??null},${b.tonsEquivalent??null},${b.status},${b.notes??null}) RETURNING *`;return c.json({data:rows[0]},201);});

  app.get('/api/v1/lease-payments',async c=>{const season=qUuid(c.req.query('seasonId')),farm=qUuid(c.req.query('farmId'));if(season.invalid||farm.invalid)return c.json({error:'invalid_filter'},400);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId');const rows=await db`SELECT lp.*,l.contract_number,l.lessor_name,l.farm_id,f.name AS farm_name,fd.code AS field_code,CASE WHEN lp.status='planned' AND lp.due_on<CURRENT_DATE THEN true ELSE false END AS overdue FROM lease_payments lp JOIN leases l ON l.id=lp.lease_id JOIN farms f ON f.id=l.farm_id LEFT JOIN fields fd ON fd.id=l.field_id WHERE lp.organization_id=${orgId} AND (${season.value??null}::uuid IS NULL OR lp.season_id=${season.value??null}::uuid) AND (${farm.value??null}::uuid IS NULL OR l.farm_id=${farm.value??null}::uuid) ORDER BY CASE WHEN lp.status='planned' AND lp.due_on<CURRENT_DATE THEN 0 WHEN lp.status='planned' THEN 1 WHEN lp.status='paid' THEN 2 ELSE 3 END,lp.due_on`;return c.json({data:rows});});

  app.post('/api/v1/leases/:id/payments',async c=>{if(!financeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id')),p=paymentInput.safeParse(await c.req.json());if(!id.success)return c.json({error:'invalid_lease'},400);if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const lease=await db`SELECT id FROM leases WHERE id=${id.data} AND organization_id=${orgId} AND status IN('active','draft') LIMIT 1`;if(!lease[0])return c.json({error:'lease_not_found'},404);const season=await db`SELECT id FROM seasons WHERE id=${b.seasonId} AND organization_id=${orgId} LIMIT 1`;if(!season[0])return c.json({error:'season_not_found'},404);const rows=await db`INSERT INTO lease_payments(organization_id,lease_id,season_id,due_on,amount,document_number,notes) VALUES(${orgId},${id.data},${b.seasonId},${b.dueOn},${b.amount},${b.documentNumber??null},${b.notes??null}) RETURNING *`;return c.json({data:rows[0]},201);});

  app.post('/api/v1/lease-payments/:id/pay',async c=>{if(!financeRoles.has(c.get('role')))return c.json({error:'forbidden'},403);const id=uuid.safeParse(c.req.param('id')),p=payInput.safeParse(await c.req.json());if(!id.success)return c.json({error:'invalid_payment'},400);if(!p.success)return c.json({error:'validation_error',details:p.error.flatten()},422);const db=neon(c.env.DATABASE_URL),orgId=c.get('organizationId'),b=p.data;const rows=await db`UPDATE lease_payments SET status='paid',paid_on=COALESCE(${b.paidOn??null}::date,CURRENT_DATE),document_number=COALESCE(${b.documentNumber??null},document_number),notes=COALESCE(${b.notes??null},notes),updated_at=now() WHERE id=${id.data} AND organization_id=${orgId} AND status='planned' RETURNING *`;if(rows[0])return c.json({data:rows[0]});const existing=await db`SELECT * FROM lease_payments WHERE id=${id.data} AND organization_id=${orgId} LIMIT 1`;if(existing[0]?.status==='paid')return c.json({data:existing[0]});return c.json({error:'payment_not_found_or_not_payable'},404);});
}
